### ISSUE TITLE
Cordova Support

### ISSUE THREAD

**Issue by ahmedkassem** [scriptPilot/app-framework#134]
Can you please add suuport for cordova like in Framework7

there is a Framework7 - Vue - Webpack Cordova Template
https://github.com/centrual/cordova-template-framework7-vue-webpack

It offers many hooks which help a lot in hybrid app building and fixing

**Comment by scriptPilot** [comment]
@ahmedkassem - Realize cordova integration is on my list! :-)

**Comment by scriptPilot** [comment]
Will be released with 1.1
