### ISSUE TITLE
GUI Helper Tool for Windows, Linux or Mac

### ISSUE THREAD

**Issue by centrual** [scriptPilot/app-framework#152]
Hello @scriptPilot 

A desktop program can be created to increase the popularity of this work with electron. It can be very helpful.

Have a great day!

**Comment by scriptPilot** [comment]
@centrual - I like your idea and add a new milestone "2.0 - Desktop program" :-)

**Comment by scriptPilot** [comment]
@centrual - Would you like to specify in detail your expectations to such a desktop program?

**Comment by centrual** [comment]
1) Manage Projects (Create, Modify, Delete)
2) Manage Firebase Things (Db, Storage, Hosting)
3) Run Commands With Buttons and see results in console output ( It can be hard, because i can't find any crossplatform console emulator )
4) Helps to manage cordova plugins and displays helpful buttons-infos for known plugins like microsoft's hot-code-push
5) Publish to [ App Store, Play Store, Amazon Store etc. ]

**Comment by scriptPilot** [comment]
@centrual - Thank you, I will consider these for the 2.0 release :-)

Most of these requested things are already part of Framework7 - but you have to use console commands:

https://github.com/scriptPilot/app-framework/blob/master/DOCUMENTATION.md

**Comment by scriptPilot** [comment]
Close this point as there is no resource for it currently - feel free to reopen it if you want to support :-)
