### ISSUE TITLE
dev-server script does not copy .babelrc file

### ISSUE THREAD

**Issue by cgudrian** [scriptPilot/app-framework#156]
Without a proper .babelrc file in the project root directory there is no ES2015 support during development.

**Comment by scriptPilot** [comment]
@cgudrian - Webpack is called in the app-framework node module folder - there you find the .babelrc file. I tested the following script in pages/home.vue and it worked well after `npm run dev` - please let me know if not for you. App Framework should keep the project folder as clean as possible :-)

```
<script>
  module.exports = {
    mounted: function () {
      [1,2,3].map(n => {
        console.log('Babel no ' + n)
      })
    }
  }
</script>
```
