### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by ahmedkassem** [scriptPilot/app-framework#193]
when running npm install -verbose in demo app folder, I get this error:

npm ERR! lwip@0.0.9 install: `node-gyp rebuild`

node v7.5.0

npm  v4.1.2

Windows 10

**Comment by scriptPilot** [comment]
@ahmedkassem - Thank you, I will check that.

**Comment by ahmedkassem** [comment]
i found the problem
you have to install python version 2 to make it work

**Comment by scriptPilot** [comment]
@ahmedkassem - I recoded the icon generation with a JS only lib, so it's quite more lightweight and without any additional installation. Please update to the newest npm version and test again - thanks!
