### ISSUE TITLE
Range slider knob not visible with iOS theme on Android

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#203]
See: https://github.com/nolimits4web/Framework7/issues/1441

**Comment by xerosanyam** [comment]
This works in the demo app.
What code should I write in my app to make it work ? 
Thanks

**Comment by xerosanyam** [comment]
@scriptPilot any updates on this ?

**Comment by scriptPilot** [comment]
Should be fixed in Framework7 V3, if not, please open new issue.
