### ISSUE TITLE
Test App Framework on Linux

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#220]
Hi there! If anybody is using App Framework on Linux I would be glad to get some feedback about special things to consider for the command line interface. Does everything work fine for you?

**Comment by Grogglex** [comment]
Sure. I'm not to helping out with these sorts of things but I'm running the framework on Manjaro Linux. What can I do to help?

**Comment by scriptPilot** [comment]
@Grogglex - For me it would be helpful if you run all CLI commands, listed in the documentation and let me know the result. Any errors? In version 1.3 there will be better progress output in the command line, but it would be helpful to identify linux issues now. Thanks a lot, Dennis

**Comment by Grogglex** [comment]
@scriptPilot Sure. I'll put together a table for you. If you need any other Linux work done let me know.

**Comment by scriptPilot** [comment]
@Grogglex - Did you have the chance to test all commands?

**Comment by Grogglex** [comment]
@scriptPilot I'll output a table for you today. Sorry, I've just been busy with work.

**Comment by scriptPilot** [comment]
@Grogglex - Any test so far? :-)

**Comment by Grogglex** [comment]
# Linux Tests (WIP)

OS Information
- Node Version 6.10.0
- Manjaro Linux
- Tested with Fish and Bash

*Remaining test will be posted soon*


|Command|Result |Notes  |
|:-:	|:-:	|:--	|
|`npm install`   	| Success   	| None   	|
|`npm run dev`   	| Success   	| None   	|
|`npm run icons`   	| Success  		| None  	|
|`npm run patch`   	| Success  		| None  	|
|`npm run minor`   	| Success  		| None  	|
|`npm run major`   	| Success  		| None  	|
|`npm update`   	| Success  		| None  	|
|`npm run check`  	| Success		|None		|
|`npm run android`  | Failure		| Path for Android Studio Wrong (Will make a PR)

**Comment by scriptPilot** [comment]
@Grogglex - Thank you very, very much for the test - I will fix the path with 1.3.

**Comment by scriptPilot** [comment]
Current development version tested successfully on Ubuntu as well.
