### ISSUE TITLE
Desktop / laptop / tablet mode

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#24]
Optionally, there should be a smartphone-like frame around the app if it's opened on a desktop or tablet screen to ensure a nice look. Maybe with wooden background and iPhone / Android frames to choice.

Bandwith-saving frame could be taken from [Framework7 homepage](https://framework7.io/)

**Comment by scriptPilot** [comment]
Kept it simple, but nice with transitions :-)

**Comment by ahmedkassem** [comment]
how can i remove the phone frame for the app in desktop view and make the app shown full screen ?

**Comment by scriptPilot** [comment]
@ahmedkassem - Set `showPhoneFrameOnDesktop: false` in package.json file.
