### ISSUE TITLE
Live Reload not working on Linux

### ISSUE THREAD

**Issue by edanweis** [scriptPilot/app-framework#245]
Webpack Live Reload is not working out of the box. Any suggestions?
Linux, Chrome, npm 3.x, node 6.9.2

I can confirm that Live Reload is working for me with this repo: https://github.com/centrual/cordova-template-framework7-vue-webpack

**Comment by edanweis** [comment]
I can confirm Live Reload is working on Windows.

**Comment by scriptPilot** [comment]
@edanweis - Thank you for reporting!

I kindly ask you to test all other CLI commands in order to test Linux compatibility.

You can reply to #220 

Thank you, Dennis

**Comment by scriptPilot** [comment]
@edanweis - Will be solved in 1.3 (tested on Ubuntu)
