### ISSUE TITLE
Android Build Problem

### ISSUE THREAD

**Issue by ahmedkassem** [scriptPilot/app-framework#253]
when running npm run android,  i get this error

Android Studio project build ongoing with application build version 1.2.71 - please wait ...
Android Studio project version 1.2.71 build, Android Studio is starting ...
(node:10116) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:1023:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by scriptPilot** [comment]
@ahmedkassem - Thanks, I will check next week. Dennis

**Comment by scriptPilot** [comment]
@ahmedkassem - Did you clone/fork the project or installed it according documentation as a module?

**Comment by ahmedkassem** [comment]
i tried both cloning the repo and getting the package.json file alone
then i ran npm install using git bash
then i ran npm run dev and it worked fine
then when running npm run android, i get this error

**Comment by scriptPilot** [comment]
@ahmedkassem - It will be fixed in 1.3 soon.
