### ISSUE TITLE
Suggestion please

### ISSUE THREAD

**Issue by kiralikbeyin** [scriptPilot/app-framework#268]
Before diving more deeper please can you make suggestions for new design? Vue and also Firebase is a new thing for me. 
Thanks.

![image](https://cloud.githubusercontent.com/assets/10079333/23398818/acb626e4-fda6-11e6-9f81-bb1cd7b8192f.png)

Alternative:
![image](https://cloud.githubusercontent.com/assets/10079333/23404222/8ea58364-fdbc-11e6-9d3b-287d615ad4ee.png)

**Comment by scriptPilot** [comment]
Hello @kiralikbeyin - App Framework is a very good choice if you would like to create Apps - as Web App or as native App for the stores. Firebase is a good backend for database and file storage. Vue makes it easy to develop reactive and state-based interfaces. For detailed questions and discussions, I would like to refer to Stackoverflow. Dennis
