### ISSUE TITLE
ES6 imports? SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by edanweis** [scriptPilot/app-framework#281]
I'm getting `SyntaxError: Unexpected token import` when trying to import modules using ES6 syntax:
```javascript
import { mixin as clickaway } from 'vue-clickaway';
```

But babel loader is configured to use .babelrc file includes ` "presets": ["es2015", "stage-2"],`

How can we enable ES6 module loading? Workaround if not enhancement.

**Comment by edanweis** [comment]
Things appear to work after copying .babelrc to the app root directory.

**Comment by scriptPilot** [comment]
@edanweis - Please could you list the steps you did to install and run the App? Where did you place the import command? Dennis

**Comment by scriptPilot** [comment]
Fixed in 1.3
