### ISSUE TITLE
Sample Apps

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#296]
I was wondering if anyone had any links to any sample apps created using this framework? In lieu of a tutorial it might be helpful if someone was willing to share an app they built to give newcomers (myself included) a sense of how to extend the demo application.

As someone fairly new to Vue/Framework7 it's not immediately clear where/how to extend the application.

**Comment by scriptPilot** [comment]
@Grogglex - A tutorial is planned. I highly recommend to you to get familar with Framework7 / Framework7-Vue before you use this Framework - docs, demos, tutorials to be found here: https://framework7.io/docs/. Does it help you?

**Comment by Grogglex** [comment]
Thanks so much for all the help scriptPilot. I am quite familiar with Framework7. I was struggling with including custom scripts in my pages but you addressed that on another question.
