### ISSUE TITLE
Where to Include Other Scripts / Dependencies

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#313]
I might be being dense but I was wondering where/how we introduce other JavaScript scripts or include other dependencies. For instance, if I wanted to include Vuex or if I wanted to add and import some JavaScript classes, where in the application structure is it suggested I do that? Thanks!

**Comment by scriptPilot** [comment]
@Grogglex - I propose the following way:

**Include JS files**

1. Save them to /lib/your-module.js
2. Load them in app.vue / or pages/....vue

   ```
   let module =  require('../lib/your-module.js')

   module.exports = { ... }
   ```

**Include npm modules**

1. Run, as example for Underscore.js, `install --save-dev underscore`
2. Load same way in file

   ```
   let _ =  require('underscore')

   module.exports = { ... use _ in your code ... }
   ```

Does this answer your question?

**Comment by Grogglex** [comment]
Thanks. I'll see if this works for me. My first instinct would be to include something like Vuex at the top level of the application and make it available as a global in the main Vue instance (new Vue) and then make the store a property of that instance. I don't know that the current architecture supports that.

**Comment by scriptPilot** [comment]
Please could you describe what you want to realize with Vuex what is not possible with the standard setup? I ask to learn :-)

**Comment by Grogglex** [comment]
Sure. So the idea is I want to access objects in different parts of the application. An example would be if I had a shopping cart and a product page. I would want to access the same 'project' object in both pages. How would you accomplish this with your framework?

**Comment by scriptPilot** [comment]
What is the source of your data?

* if database > use firebase as shown in the public firebase todo list
* if file > include json from several pages
* use local storage

In general, all data you have added once to the page component data object, will be restored after application reload, even there is no internet connection anymore.

Does it help you?

**Comment by scriptPilot** [comment]
Each page object share the same $root object, which you can use as common storage. Then make computed data on page object and you have your reactive App. Does this help?

**Comment by Grogglex** [comment]
Yeah, I see how what you mean, you can attach things to the this.$root of each page object but I don't think it's best practice really.  https://vuejs.org/v2/guide/state-management.html Vuex also integrates into the Chrome development tools which allows for really wonderful debugging of the application.

**Comment by scriptPilot** [comment]
@Grogglex - there will be a demo in v1.3 ( #315 ) how to include own modules. For Vuex, feel free to open a new issue if you would like to have it in the future as extension.

**Comment by yipcma** [comment]
same question here, wonder what's the rationale of not exposing the main.js/vue instance.

**Comment by scriptPilot** [comment]
@yipcma - Please can you specify what you are missing?

**Comment by yipcma** [comment]
@scriptPilot so there usually is the Vue instance that I could add components to etc. I'm curious how to access it and add components, such as using veux or calling other npm modules that requires setting up a vue component in the instance.

**Comment by scriptPilot** [comment]
@yipcma - OK, now I got your point. The objective was to shift all the recurring stuff to App Framework. So, do you have some more examples in addition to Veux? I've created a new issue for follow-up: https://github.com/scriptPilot/app-framework/issues/593

**Comment by Grogglex** [comment]
@yipcma I maintain a fork with Vuex.

https://github.com/Grogglex/app-framework/releases/tag/custom_v0.0.3

You can install it with by having:

`app-framework: https://github.com/Grogglex/app-framework/releases/tag/custom_v0.0.3`

I plan on maintaining that fork (the only difference is that it uses Vuex).

in your package.json
