### ISSUE TITLE
Question: Adding Cordova Plugins

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#334]
Hey SP, sorry to be asking so many questions (but maybe it'll help when it comes time to expand the docs). How would you go about adding extra cordova plugins to the application since the Framework doesn't seem to provide direct access to Cordova. Thanks!

**Comment by scriptPilot** [comment]
@Grogglex - You have to add them in the package.json file (>1.3 in the app/config.json file) in the property array `useCordovaPlugins ` :-)

**Comment by Grogglex** [comment]
Thanks @scriptPilot, that works. I had an unrelated question. I was wondering if you were looking for a hand doing any of the maintenance of this project? I am really quite impressed so far and would love to do anything I could to help out. (This would be my first time contributing to an open source project).

**Comment by scriptPilot** [comment]
@Grogglex - Thank you for your offer! I will see how to involve you in the future the best way. For now, you really help me with testing :-)

**Comment by Grogglex** [comment]
@scriptPilot Quick question, after you add the plugins what command do you run to have them added to the project? For instance, I added the device plugin in the array but I'm not sure what command I need to run in order to have them added to the browser project.

**Comment by scriptPilot** [comment]
@Grogglex -  I just released version 1.3. You would help me a lot if you test the new release with following the readme file and documentation step by step and let me know any typo or issue :-)

**Comment by Grogglex** [comment]
@scriptPilot Sure. I'll test out all the scripts ASAP (anything else to test?)

I asked a question earlier and deleted it; I was wondering, is it possible to use the cordova plugins in the browser version of the application? For instance -> https://github.com/apache/cordova-plugin-device indicates that the device plugin is available for browser so that you can reference 'browser' globally?

**Comment by scriptPilot** [comment]
@Grogglex - Currently, cordova plugins are only added on Xcode and Android Studio builds.

**Comment by scriptPilot** [comment]
@Grogglex - Script AND DOCUMENTATION would be great :-)
