### ISSUE TITLE
Able to build via Phonegap Build?

### ISSUE THREAD

**Issue by maplerichie** [scriptPilot/app-framework#364]
I developed iOS and Android apps with Framework7 for almost 2 years.
I do realize Vue+F7 long time ago but now just start to have interest to it.
After read through the docs, it didnt mentioned the build method via Phonegap Build, so is it mean that have to build manually?
There is a problem for me whereby i'm a "loyal" Windows user so I cant build iOS application without Phonegap Build
TQ

**Comment by scriptPilot** [comment]
@maplerichie - As there are some confusions with Cordova / PhoneGap naming, please could you specify your current workflow and the output please ... maybe some helpful documentation links to the services / libs you use? For now, App Framework uses Cordova to build an Xcode project, then you open Xcode to build the package for the App Store.

**Comment by scriptPilot** [comment]
As there is no response for one month now, I close the issue.
