### ISSUE TITLE
Option to disable Firebase

### ISSUE THREAD

**Issue by M4v3R** [scriptPilot/app-framework#368]
I really like the idea of app-framework, but I don't want to use it with Firebase (I will be using it as a frontend to Meteor backend application). Currently I don't see a way to easily disable Firebase - if I remove the API key from the configuration file I get errors. Are there plans to allow disabling Firebase functionality altogether? Will you accept a pull request if I implement such feature?

**Comment by scriptPilot** [comment]
@M4v3R - Thank you for your feedback, I add it to the next release 1.4

**Comment by scriptPilot** [comment]
@M4v3R - In v1.4 you could disable firebase (and its inclusion in the code) completely:

```
"firebase": {
    "useDatabaseService": false,
    "useStorageService": false,
    "useEmailLogin": false,
    ...
  }
```
