### ISSUE TITLE
Deploy directly to device during tests

### ISSUE THREAD

**Issue by dawadam** [scriptPilot/app-framework#429]
With Cordova, it's possible to deploy on Android device directly, without opening Android Studio.
Why it's not possible with app-framework ?

**Comment by scriptPilot** [comment]
The reason is to let the user decide on which emulator/simulator or own device he wants to run the app without having to much different CLI commands. Is it a show stopper for you?

**Comment by dawadam** [comment]
I have problems with Android Studio on my Linux distribution, bugs and very slow.
Is it possible to add a new command to start directly?

**Comment by scriptPilot** [comment]
@dawadam - Will be part of next release!

**Comment by scriptPilot** [comment]
Solution was buggy, so shifted to another release.

**Comment by asolagmbh** [comment]
Sorry guys but i really don't understand how to do it.
