### ISSUE TITLE
Webpack loops when running npm install -> npm run dev on /app

### ISSUE THREAD

**Issue by thechrise** [scriptPilot/app-framework#492]
Webpack seems to never finish building the /app folder.

**Comment by scriptPilot** [comment]
@thechrise - Chris, please could you help me with some details so that I can help you?

- please describe the issue a bit more in detail
- please copy the console output
- please let me know your OS, Node and App Framework version

Thanks,

Dennis

**Comment by scriptPilot** [comment]
I will reopen this issue upon your response with the requested details.

**Comment by thechrise** [comment]
Hey @scriptPilot, sorry for the lack of clarification.

Creating a new app folder works, but trying to open the demo app doesn't. I just tried again this morning... I clone the repository, cd into the app folder, add the generic package.json file, npm install, and npm run dev. When I run dev, webpack starts building, and eventually, it'll say webpack build done, but then it'll output "webpack build process ongoing- please wait ..." again. It looks like there's a code-conformities.log, but it quickly deletes itself and starts the loop over. When I run "npm run reset-app", that works but results in the basic app.

I'm running on Mac OSX 10.12.4, NPM 3.10.10, Node 6.10.3, and app-framework 1.4.23.

Thanks for your help.

**Comment by scriptPilot** [comment]
`... I clone the repository ...`

@thechrise - Please follow the documentation ... App Framework must be installed as a module:

https://github.com/scriptPilot/app-framework/blob/master/DOCUMENTATION.md#setup-your-project

Please let me know if you have still some trouble!

Regards
