### ISSUE TITLE
How to use sass in project

### ISSUE THREAD

**Issue by sizmamani** [scriptPilot/app-framework#493]
I want to know if its possible to add sass to the project

**Comment by scriptPilot** [comment]
@sizmamani - Currently not.

**Comment by ryanmstokes** [comment]
This is possible by doing the following:

1. Install the following packages:
    npm install sass-loader node-sass --save-dev

2. Set the lang property of the script tag
    <script lang="sass">
         .parent{
            .child{
            /* ... */
            }
          }
    </script>

**Comment by sizmamani** [comment]
Thanks @ryanmstokes
