### ISSUE TITLE
Would like to contribute some features

### ISSUE THREAD

**Issue by monkeybrother65** [scriptPilot/app-framework#532]
I don't know if there is a different way to do this, but I would like to contribute a feature that is important to my company and our workflow.  I have hacked app-framework to be able to use altered versions of the core framework7 less files instead of the css output.  This is important for how my designers apply branding.

How do I become a contributor?  Is there a way we could discuss that process?

**Comment by scriptPilot** [comment]
@monkeybrother65 - Now it's possible, I updated the development documentation accordingly:

https://github.com/scriptPilot/app-framework/blob/master/DEVELOPMENT.md

Please let me know any open question.
