### ISSUE TITLE
Add Additional Paths to Webpack?

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#586]
Hey SP. Sorry I've been away but I'm back now and around to help where I can. I just wanted to ask, is there a way to add more directories to the auto reload? For instance, I have a folder, 'app/components/labels/food.vue' but the current setup doesn't seem to pick up changes in that directory. Can you think of a simple way of getting live-reloading to work for components? Alternatively, where in your mind should components live (that aren't pages)? In app/pages/components?

**Comment by Grogglex** [comment]
I think organizing content under pages is fine but I was just wondering if additional directories might be added as a feature in the future (in a config file maybe).

**Comment by scriptPilot** [comment]
@Grogglex - I will check that next week after my vacation. Dennis

**Comment by scriptPilot** [comment]
@Grogglex - It should work automatically.

I created the file *app/components/labels/food.vue*

```
<template>
  <div>Test 123</div>
</template>
```

Then included it in any page component:

```
...
  components: {
    test: require('../components/labels/food.vue')
  }
```

Started the server with `npm run dev`

Changed the file *food.vue* to `... Test 123 456` and Webpack updated the dev-server.

Let me know if it does not work for you.

**Comment by Grogglex** [comment]
Hi SP. That does work for me. I was talking more about if you wanted to add additional folders to your base demo application. Like, at the root of my application I have a folder called "lib" where I put some JavaScript files but changes in that folder don't trigger a reload of the application.

**Comment by scriptPilot** [comment]
As long as you do not require these new files, there will be no trigger to update.
