### ISSUE TITLE
Use custom Framework7 parameters on App initialization

### ISSUE THREAD

**Issue by drunkod** [scriptPilot/app-framework#587]
Please tell me how to properly initialize and change the configuration (swipePanel: 'left')?
How to activate swipePanel?

Example from the documentation:
// Init Vue App
new Vue({
    // App Root Element
    el: '#app',
    // Init Framework7. All Framework7 parameters should be passed in "framework7" property, e.g.:
    framework7: {
        // App Root Element, should be the same as the component root "el"
        root: '#app',
        // Array with app routes
        routes: [...]
        // Any other parameters, e.g.
        animateNavBackIcon: true,
        swipePanel: 'left'
    },
    // App root data
    data: {
        // ....
    },
    // App root methods
    methods: {
        // ....
    }
})

Example from the documentation:
var myApp = new Framework7({
    pushState: true,
    swipePanel: 'left',
    // ... other parameters
});

**Comment by scriptPilot** [comment]
@drunkod - As App Framework does the initialization, its a new feature to realize. I will take a look on it after vacation next week. Dennis
