### ISSUE TITLE
On Build: ERROR: Failed to read image files 

### ISSUE THREAD

**Issue by capgros** [scriptPilot/app-framework#588]
I'm trying to build my app for android:
First making a build: 
`npm run minor`

But it trows an error where it didn't in previous builds:

> Error: ENOENT: no such file or directory, scandir 'C:\Users\Miguel\Projects\mys\node_modules\.app-framework-cache\build\www\img'

I'm a first timer with webpack but it looks like in file 189 of build.js it's looking for the `img` folder:

>let compressImages = function (callback, files) {
  if (files === undefined) {
    alert('Images compression ongoing - please wait ...')
    rec(abs(env.cache, **_'build/www/img')_**, function (err, files) {
      if (err) {
        alert('Failed to read image files.' + err, 'issue')
      } else {
        compressImages(callback, files)
      }
    })

when webpack is puting cached images it in `images` folder
>// Image files
>    {
>      test: /\.(png|jpe?g|gif)(\?.*)?$/,
>      loader: 'url',
>      query: {
>        limit: 1,
>        name: **_'images/_**[name].[hash:7].[ext]'
>      }

I've tried modifying img to images and it worked.

Is this a bug or i'm doing something wrong?

I take the opportunity to tell you that your framework is awesome.

**Comment by scriptPilot** [comment]
Hello Miguel,

Looks like a bug. I will deal with it next week after vacation.

Thanks for reporting,

Dennis



capgros <notifications@github.com> schrieb am Fr. 2. Juni 2017 um 13:25:

**Comment by scriptPilot** [comment]
Hello Miguel,

Looks like a bug. I will deal with it next week after vacation.

Thanks for reporting,

Dennis

**Comment by Mine1590** [comment]
Yes same issue here, same fix how's everyone else doing it? thank you very much for this it's an awesome framework!

**Comment by capgros** [comment]
I just updated and it worked. As a workaround you can modify webpack's
build.js script as I mention in my first message.
