### ISSUE TITLE
Bug: Tab Bar Stops Working if Query Parameter in Navbar Local Storage

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#590]
Hi SP,

I've found a really strange bug, maybe you might have some insight into it. In my application I notice that different pages get pushed into the local storage key `urls|#main-view.view.view-main.navbar-fixed.navbar-through` to keep track of where the user is in the application. I've noticed that if there is a query parameter in one of the routes than the tabbar element's tabs stop working.

You can test it by going to: https://strollopia.firebaseapp.com/ and then go to Strolls, where you'll see three tabs. If you insert the following in the localStorageKey I mentioned above, `home?test=1` you'll notice that the tab bar stops responding/switching views on click. I think it breaks because of the `?` character.

Maybe the way I'm constructing routes is what's causing it? 

`      <f7-list-item v-for="map in active" @swipeout:deleted="toggleStroll(map)" :title="map.name"
            :subtitle="map.description" :text="map.text" after="More"
            :link="'stroll/?strollId='+ map.id" swipeout>`

What would the proper way of constructing a link with a param be?

Thanks as always for your hard work.

**Comment by Grogglex** [comment]
I alos noticed that my key seems rather long: `urls|#main-view.view.view-main.navbar-fixed.navbar-through`

**Comment by scriptPilot** [comment]
Do you have a repo to test?

**Comment by Grogglex** [comment]
Hi SP. I'm not very happy with how I've worded this issue. I'm going to close it and when I have a small, reproducible demo using the demo app I'll make a new issue that demonstrates it if I'm able to reproduce it using the base demo application. Sorry about that.

**Comment by Grogglex** [comment]
Hi SP, 

So the issue I was actually having with this is that it seems that if you setup navigation a certain way you end up in a situation where you have multiple instances of the same component around which is the actual root cause of this problem. There's not an example in the demo app but I'll make one so that you can see.

So essentially if you navigate like this:  home -> about -> another_page -> home you end up in a situation where you have two instances of the home component.

**Comment by Grogglex** [comment]
Hi SP, so here's an example of that bug

https://github.com/Grogglex/af_bug_example

Basic there's the home page that links to the second page which has a tabbar and then that links to a third page that contains a link to the second page. It's a contrived example but this kind of thing would happen with a side nav or other kinds of navigation. You'll see after visiting the second page for the second time the tab bar stops working.

**Comment by Grogglex** [comment]
I'm going to move this to a new issue.

**Comment by Grogglex** [comment]
Whoops. I'm going to move this to a new issue.
