### ISSUE TITLE
Allow custom preroutes or more options for permissions based viewing

### ISSUE THREAD

**Issue by codingfriend1** [scriptPilot/app-framework#591]
I need to be able to selectively load routes based on a user's role or permission. For instance only admin's can load the edit-users page, or only user's with a permission of 'create-page' can go to the create-new-page page. 

Could you create a way to allow us to override custom preroutes? Perhaps calling your current preroutes method as a helper?

**Comment by scriptPilot** [comment]
@codingfriend1 - Get that point. I add is as feature request.

**Comment by miner150000** [comment]
Meanwhile you could use the Dynamic routing for this purpose as you could send a boolean depending on the user's permissions.

Example:
User Miner permission Root
User Pilot   permission non-root

`Routes
{
    "path": "/create-page/:permission/",
    "component": "createPage.vue"
 },`

then Test User permission and link accordingly
`if (user.permission==="root"){ window.f7.mainView.loadPage('/create-page/true');
else{window.f7.mainView.loadPage(/create-page/false)}`

not perfect and very enhanceable but you get the point.

**Comment by scriptPilot** [comment]
@codingfriend1 @miner150000 - Find here the final solution: https://github.com/scriptPilot/app-framework/blob/master/docs/extend-vue-root-object.md
