### ISSUE TITLE
`npm run android` failed - Float types not allowed for 'versionCode'

### ISSUE THREAD

**Issue by codingfriend1** [scriptPilot/app-framework#592]
Not sure if I'm doing something wrong but I'm attempting to test the app on my android phone without upgrading the app version.

BUILD FAILED

Total time: 17.821 secs
Error: /Users/me/Desktop/POCS/app-framework-fast/node_modules/cordova/bin/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/me/Desktop/POCS/app-framework-fast/node_modules/cordova/bin/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:5:26-39: AAPT: Float types not allowed (at 'versionCode' with value '1497225347745').
    
/Users/me/Desktop/POCS/app-framework-fast/node_modules/cordova/bin/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml:2: error: Error: Float types not allowed (at 'versionCode' with value '1497225347745').

FAILURE: Build failed with an exception.

**Comment by scriptPilot** [comment]
@codingfriend1 - Can you please let me know your setup? (OS / App Framework version) - thanks!

**Comment by codingfriend1** [comment]
Sorry. OSX v 10.12.4
app-framework version: 
"app-framework": "^1.9.0"

Android Studio version 2.3
Gradle 3.3
Android Plugin version: 2.3.3

**Comment by xupateste** [comment]
The same error here.

OS: 10.12.5
App-framework: 1.9.6
Android Studio: 2.3
Android SDK Tools: 26.0.2
Android Platform Version: API 26:Android 8.0(0) revision 1

Did you solve it?

**Comment by scriptPilot** [comment]
So, I checked with macOS 10.12.5 / App Framework 1.9.10 / Studio 2.3.1 ... no issue for me, so I have to go more into details.

**Comment by scriptPilot** [comment]
The number `1497225347745` should be an integer in fact (https://www.w3schools.com/js/js_numbers.asp) ... strange

**Comment by scriptPilot** [comment]
@codingfriend1 @xupateste - Please check with 1.9.11, issue should be fixed.
