### ISSUE TITLE
Make it possible to edit root vue component

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#593]
Linked to https://github.com/scriptPilot/app-framework/issues/313#issuecomment-307652007

**Comment by yipcma** [comment]
Just expose the instance and let developers configure their components would be excellent. I just don't understand why you hide the instance in the first place.

**Comment by scriptPilot** [comment]
See the docs: https://github.com/scriptPilot/app-framework/blob/master/docs/extend-vue-root-object.md
