### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#594]
cli
- mkdir ...
- cd dir ...
- echo {} > package.json
- install --save-dev app-framework

postinstall
- add default name
- add default version

remove error
```
/Users/dennis/Documents/GitHub/app-performance/node_modules/app-framework/scripts/postinstall.js:139
  if (env.pkg.devDependencies['app-framework'] === '*') {
                             ^

TypeError: Cannot read property 'app-framework' of undefined
```

**Comment by paynestrike** [comment]
I got the same error

**Comment by scriptPilot** [comment]
@paynestrike - In fact that is not an error - that kind of installation is not implemented. Please follow the documentation and let me know if you still have issues.

**Comment by paynestrike** [comment]
I don't understand, that's the error I got, and I did follow the installation  document. Please help me install this app framework

**Comment by paynestrike** [comment]
I get it. you can't run "npm install app-framework --save-dev", app-framework must in devDependency before "npm install".

**Comment by scriptPilot** [comment]
@paynestrike - Again, please follow the documentation step by step and you won't get into trouble: https://github.com/scriptPilot/app-framework/blob/master/docs/setup.md

**Comment by augmen** [comment]
@scriptPilot , hi script pilot . i am trying to develop a video library of app-framework . kindly guide on step / step command to get started on mac terminal. i am followed the docs , but are not sufficient. can we talk . can you help us on the project ?

**Comment by augmen** [comment]
@scriptPilot got this error 
`npm ERR! If you do, this is most likely a problem with the app-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app-framework
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /User/app-F/npm-debug.log`

please guide

**Comment by scriptPilot** [comment]
@augmen - If you have any error message, please open a **new issue** and provide your operating system, the steps you did and the error log. Thanks
