### ISSUE TITLE
Firebase reference 

### ISSUE THREAD

**Issue by jrvidotti** [scriptPilot/app-framework#600]
Sorry for the noob question. How can I reference a Firebase document collection directly from template, like in vue-fire package?

```
<template lang="pug">
  f7-page
    f7-navbar(:title="$root.config.title")
    f7-block(inner inset) Tickets
    f7-list
      f7-list-item(v-for="ticket in tickets") {{ticket}}
</template>

<script>
export default {
  firebase: {
    tickets: window.db('tickets')
  }
}
</script>
```

The above code results in error:
`[Vue warn]: Property or method "tickets" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`

**Comment by scriptPilot** [comment]
@jrvidotti - You have to create your own routine to update values either in the global data object or the page data object. Then you can easily reference in the template ... please see the demo source code for details: https://github.com/scriptPilot/app-framework/blob/master/demo/pages/firebase-public.vue

Does this answer your question?

**Comment by jrvidotti** [comment]
It worked! Thank you very much!
