### ISSUE TITLE
Own provider for User Authentication

### ISSUE THREAD

**Issue by capgros** [scriptPilot/app-framework#601]
Hi,
I've been trying it for a while but I can't understand how to plug current authentication (routes login:true) with my own authentication system.
I have all my users in a mysql database and planed to acces it via API, but I would like to integrate it with your current system instead of firebase.
Is that too dificult? Maybe you could address me where to look at?

Thank you for your kind help.
Miguel

**Comment by scriptPilot** [comment]
Hi Miguel, your issue is linked to https://github.com/scriptPilot/app-framework/issues/593 and already considered as new feature!
