### ISSUE TITLE
setup question

### ISSUE THREAD

**Issue by opichon** [scriptPilot/app-framework#604]
The setup docs suggest adding ap-framework as a dev dependency. Wouldn;t it be simpler to just git clone the app-framework?

If app-framework is  installed as suggested by the setup docs, then the `npm run xxx` commands` are not available (unless copied). In fact, any of the 1npm run xxx` commands suggested elsewhere in the docs trigger this error: `missing script xxx`. This is normal, since my app's package.json does not define any script. 

AmI supposed to copy the scripts from node_modules/app-framework/build to my own `build` dir? If that's the case, where is the docs for this? I'd have to copy the build directory, then update package.json, etc.  I'm sorry if I missed this, but I don't remember seeing any of this in the docs. The docs hust seem to assume that the `npm run` scripts would be there.

This is very confusing.

**Comment by ddela-cr** [comment]
After running `npm install`, you should have scripts in your package.json

**Comment by opichon** [comment]
Thanks for the quick reply. yes, this time the `npm install` command did add scripts to package.json, plus it created a number of directories. That didn;t happen the few times I previously  tried to run it, hence mhy confusion.

**Comment by scriptPilot** [comment]
Please follow the documentation for setup:

https://github.com/scriptPilot/app-framework/blob/master/docs/setup.md

**Comment by opichon** [comment]
For your info, I ran `npm install` several times, following the instructions in the setup docs, but the directories did not get created and the scripts did not get added to `package.json`. You also may want to add some explanations of what happens in the setup docs, so that in case the process fails (as it did in my case), users do not end up confused.
