### ISSUE TITLE
this.$f7 is undefined

### ISSUE THREAD

**Issue by opichon** [scriptPilot/app-framework#606]
Inside the app component, `this.$f7` appears to be undefined.

I am using the loginc from the app-component.md docs, namely adding thisto app.vue:

```
<script>
  export default {
    mounted: function () {
      this.$f7.alert('App is mounted!')
    }
  }
</script>
```

In the browser, the following error is reported:
```
vue.common.js:525 TypeError: Cannot read property 'alert' of undefined
    at VueComponent.mounted (app.vue:40)
```

If instead I just do `console.log(this)` then I can see that there is no $f7 property.

**Comment by jrpereirajr** [comment]
Same here, just `this.$f7Router` is available.

**Comment by scriptPilot** [comment]
@opichonm @jrpereirajr - Documentation is updated, thanks - please follow Framework7 way of working:

```
methods: {
  onF7Init: function () {
    this.$f7.alert('Page is mounted!')        
  }
}
```
