### ISSUE TITLE
Improve performance for Android Jelly Bean (v4.2.2)

### ISSUE THREAD

**Issue by Premke** [scriptPilot/app-framework#608]
It seems [App Framework Demo](https://play.google.com/store/apps/details?id=de.scriptpilot.appframework) is not working on Android Jelly Bean.

**How to reproduce**:
1. Install Android Studio
1. Configure and start AVD with Jelly Bean
1. Install App Framework Demo on it (or your custom app based on the framework)

**Result**: 
App is stuck on loading overlay.

I think this is App Framework's related problem and not Cordova's (since my other cordova related apps that are built with Framework7 but without the framework are working correctly).

Also Chrome DevTools Inspect (`chrome://inspect/#devices`) is not working for me for Jelly Bean which makes debugging harder.

Any ideas, suggestions?

**Comment by scriptPilot** [comment]
@Premke - Maybe there are performance issues, but I cannot give a prompt answer to you - sorry.

**Comment by scriptPilot** [comment]
V3 will not give special attention to Android v4 anymore, as the official support is stopped long time ago
