### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by arturcesarmelo** [scriptPilot/app-framework#611]
I'm sory if a didn't understand pretty well but, when i follow the [workflow](https://github.com/scriptPilot/app-framework/blob/master/DOCUMENTATION.md) and finish the instalation, [this folder structure](https://github.com/scriptPilot/app-framework/blob/master/docs/dev-folder-structure.md)

![captura de tela 2017-06-22 as 15 38 59](https://user-images.githubusercontent.com/18191910/27450121-00e98cce-5761-11e7-878e-2a2ddb51aff2.png)

Does not seems to be like that

![captura de tela 2017-06-22 as 15 42 09](https://user-images.githubusercontent.com/18191910/27450230-641bdc84-5761-11e7-98af-99d3ab37ebb1.png)

I'm a beginner in app development and many people comes to me to say: "a good idea is to see the documentation". I'm a new bye in app development, but not in development at all. I think that is complicated to know how something works when the documentation does not match with the reals results. I used AngularJs for many years and was hard to me at beginning. So i'm sorry if i miss something.

Is there anything wrong?

**Comment by scriptPilot** [comment]
Hey, it seems you took a look into the App Framework developers docs - please read this chapter for the correct folder structure: https://github.com/scriptPilot/app-framework/blob/master/docs/folder-structure.md

**Comment by arturcesarmelo** [comment]
Thank you, dude.
