### ISSUE TITLE
How to setup a single css file in a project?

### ISSUE THREAD

**Issue by arturcesarmelo** [scriptPilot/app-framework#612]
I'm having a lot of work to reply css codes because i can't find in anywhere when i should put the css files "globaly" in the project. Doesn't have a index file... Can anyone help me?

**Comment by scriptPilot** [comment]
Please read this chapter: https://github.com/scriptPilot/app-framework/blob/master/docs/app-component.md

**Comment by arturcesarmelo** [comment]
It's so good when the repository's owner answer back as fast as we wish. Thank you so much. Now i see that i made a beginner error.
