### ISSUE TITLE
The icons lib doesn't work.

### ISSUE THREAD

**Issue by arturcesarmelo** [scriptPilot/app-framework#613]
Seems like it is not installed in dependencies... and... npm install should install it. What is wrong?

**Comment by scriptPilot** [comment]
Pleas can you specify a) what you want to do and b) what happens? Icon libs have to be activated in the "app/config.json" files.

**Comment by scriptPilot** [comment]
Please read the documentation and let me know any open issue: https://github.com/scriptPilot/app-framework/blob/master/docs/icon-fonts.md
