### ISSUE TITLE
Add build/ to .gitignore

### ISSUE THREAD

**Issue by M4v3R** [scriptPilot/app-framework#614]
Shouldn't `build` directory be added to `.gitignore`? It does not make sense to have it in the repo, but then if I add it manually it will revert on any app-framework updates. Plus, it breaks `npm run xcode` command (`build` directory doesn't get copied over to app bundle).

**Comment by scriptPilot** [comment]
@M4v3R - Can you please add information to your issue ... so, what is your system, which errors you get while running npm run xcode?

**Comment by mfkenson** [comment]
it seems that @M4v3R reported two things.

1. He wants the .gitignore file includes `build/` directory. Currently the .gitignore file is re-generated on every build. I also want to customize my .gitignore file. I want to exclude the IDE config files.

2. Second issue is that `npm run xcode` does not use latest project source. I agree that

**Comment by capgros** [comment]
It would be great to be able to edit .gitignore and add custom folders.

Also add build folder in default .gitignore file as it's not source.

**Comment by scriptPilot** [comment]
Rollback

**Comment by scriptPilot** [comment]
Done in V3, can be configured if needed.
