### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by teddysasmita** [scriptPilot/app-framework#617]
^[cCopying icon file - please wait ...

^[cError: Failed to copy icon file.

Please open an incident on GitHub:
https://github.com/scriptPilot/app-framework/issues

^[cError: Failed to setup app folder.

Please open an incident on GitHub:
https://github.com/scriptPilot/app-framework/issues

**Comment by scriptPilot** [comment]
@teddysasmita - Please can you add details about your system and the steps you performed?

**Comment by teddysasmita** [comment]
I am using Ubuntu 17.04 and NodeJs 6.11 with its npm. Thank you.

**Comment by axjs** [comment]
same issue.
>>Error: Failed to copy icon file.

Ubuntu 16.04.2 x64
node v8.1.2

**Comment by axjs** [comment]
[https://github.com/scriptPilot/app-framework/blob/master/scripts/reset-app.js#L34](https://github.com/scriptPilot/app-framework/blob/master/scripts/reset-app.js#L34)

`fs.copy(abs(__dirname, '../demo/icon.png'), abs(dest, 'icon.png'), function (err) {`

from version 1.9.6 folder ../demo not included in npm package

**Comment by scriptPilot** [comment]
Should be fixed with 1.9.7, please let me know there are still issues!

**Comment by axjs** [comment]
Solved in 1.9.7 
@scriptPilot thanks for fix

**Comment by teddysasmita** [comment]
Installation process is success.
Thank you for the fix.
I cannot wait to try your framework.
