### ISSUE TITLE
router history mode

### ISSUE THREAD

**Issue by yuantw** [scriptPilot/app-framework#619]
I would like to have a direct link to a page with parameters. I can get it working by 

```
Vue.use(Router)

const router = new Router({
  mode: 'history',
  routes: [
        {
      path: '/chat/:id',
      name: 'Chat',
      component: Chat
}]
```

How can I do the same thing within App-Framework?

**Comment by scriptPilot** [comment]
Please find details in the docs: https://github.com/scriptPilot/app-framework/blob/master/docs/routing.md
