### ISSUE TITLE
Cannot resolve favicon.ico in npm run dev

### ISSUE THREAD

**Issue by lcaprini** [scriptPilot/app-framework#627]
I have the following error with `npm run dev`:
```
ERROR in ./~/app-framework/client/init.js
Module not found: Error: Cannot resolve 'file' or 'directory'
../../.app-framework-cache/icons/dev/favicon.ico in .../node_modules/app-framework/client
 @ ./~/app-framework/client/init.js 25:2-72
```
Webpack doesn't create `index.html` page and I obtain a `Cannot GET /` error.

When I commented
`require(process.env.CACHE_ROOT_FROM_SCRIPTS + 'icons/dev/favicon.ico')`
 at `app-framework/client/init.js:30`, all works fine, obviously.

Thank you.
-L

**Comment by scriptPilot** [comment]
@lcaprini - Please can you show a screenshot of your folder "app" ?

**Comment by lcaprini** [comment]
This error occurs since first run, after the `npm install`. This is my situation:
<img width="222" alt="app" src="https://user-images.githubusercontent.com/8091030/27877330-7be22716-61ba-11e7-8780-5f6dc2c35020.png">

**Comment by scriptPilot** [comment]
@lcaprini - Is the issue fixed for you when you try with a clean installation according the docs?

**Comment by meteozond** [comment]
We've ran into this problem at latest framework update. For a some reason not all icons were generated.
Fresh installation works fine as like as removing and farther `node_modules/.app-framework-cache` folder regeneration during next build.

**Comment by scriptPilot** [comment]
@meteozond - Thank you for that solution.
