### ISSUE TITLE
Multiple instances of components get created with non-linear navigation

### ISSUE THREAD

**Issue by Grogglex** [scriptPilot/app-framework#632]
HI SP,

So I had an issue awhile ago I thought was caused by query parameters but it's actualy caused from non-linear navigation. If you navigate non-linearly (`home -> about -> tutorial -> home`) you end up with multiple instances of the same component. As a side note when this happens the tab bar component stops working. 

If the answer is to make sure your application's navigation is linear to avoid navigating to different parts of the application from other parts, then that's OK, I can revamp my current application.

Just wondering what your thoughts are on this. I've made a demo repo to demonstrate the bug / what I mean: https://github.com/Grogglex/af_bug_example

Thanks as always for your hard work.

**Comment by scriptPilot** [comment]
@Grogglex - I discovered the same behavior. Should be a Framework7-Vue thing, what do you think?

**Comment by Grogglex** [comment]
Ah. You're probably right about that. One way of testing I guess would be to build a simple app like I did but using just Vue F7. Do you have a bug open with F7 about it? If not I can do it.

**Comment by scriptPilot** [comment]
As I have currently not so much time for coding, I would appreciate if you create a jsfiddle example of F7-Vue, an issue and link it here.

**Comment by scriptPilot** [comment]
@Grogglex - Did you raise any issue to Framework7-Vue?

**Comment by scriptPilot** [comment]
https://github.com/framework7io/Framework7-Vue/issues/263

**Comment by scriptPilot** [comment]
Issue is treated here:

https://github.com/framework7io/Framework7-Vue/issues/263

As a workaround, you can:

a) Add `:domCache="false"` as parameter to any <f7-view> object
b) Work with tabs

Close the issue here as it is related to F7-Vue.
