### ISSUE TITLE
[Question] So confused. How is this different from Framework7?

### ISSUE THREAD

**Issue by JPBuenaventura** [scriptPilot/app-framework#636]
I dunno if this is the appropriate channel to ask this but how does this differ from Framework7?

**Comment by capgros** [comment]
Hello JPBuenaventura,
This framework is a kind of wrapper that automatizes most of the boilerplate job you need to do when using Framework7 + vue.

It includes webpack configuration for easy development and some options to make an easier starter point forn an app. For example easy firebase integration or automatic route creation.
The most similar and 'vanilla' would be the [framework7 Vue Webpack Template](https://github.com/nolimits4web/Framework7-Vue-Webpack-Template).

This channel is more appropiate for bugs or requests regarding the framework. I don't know if there is any other channel to ask questions regarding usage.

I hope my answer provided some help.
Sorry for my English!

**Comment by JPBuenaventura** [comment]
That makes perfect sense. I'm new to Framework7 and I intend to use it to develop hybrid apps. 
I used this (App Framework) and the vanilla Webpack + Vue and I found that using this instead of the vanilla one increases the productivity.

Thank you for the response :)
