### ISSUE TITLE
Remove basic node modules from Webpack build

### ISSUE THREAD

**Issue by miner150000** [scriptPilot/app-framework#642]
This is not an issue per se but maybe i can help with others having trouble when installing dependencies that use the modules that come with node

i finally resolved this problem when installing any module that uses basic node modules like FS or CHILD_PROCESS (this two were my case but there are many more).

the problem was that when installed some of this dependencies the build was ok but in the console it showed that it couldn't find fs and child_process, how can it be! these come shipped with node!.

well the problem by itself is also (as many others) not related with the framework but with the way web pack does the compilation.

basically we have to tell web pack not to compile into the bundle this shipped modules as web pack tries to find them in your package.json and can't find them (because they come with node) so it throws an error and everything goes bust (it stays in the loading page if you test it on mobile)

the fix:
what you will find everywhere is to modify the webpack build file but, in our framework this file is also generated, so we have to change a different line than the one you find on the web

depending on your error you have to put the exceptions in the top part where the config object is instantiated
so add this at the end of the instantiation (i had the fs and child-process errors but modify to your needs)

node:{
  fs:"empty",
  child_process:"empty"
}

That's it!

Again thank the developers for this awesome framework as it has been great for my project

**Comment by scriptPilot** [comment]
As there are no issues with App Framework I close this issue. But anyway, thank your for your effort to help other users :-)
