### ISSUE TITLE
how to use cordova-plugin-camera?

### ISSUE THREAD

**Issue by cnusrso** [scriptPilot/app-framework#646]
i have add 'cordova-plugin-camera' to my project's config.json  useCordovaPlugins .
and call window.cordova.plugin.camera in js, it's say cordova is undefined!!!
why? how to use camera ?? thanks.
my test platform is win32,and use chrome,node version is 6.10.0

**Comment by scriptPilot** [comment]
I understand you've tested in the browser (Chrome). Plugins are available only in native applications or in an emulator. I've updated the documentation: https://github.com/scriptPilot/app-framework/blob/master/docs/cordova-plugins.md

**Comment by cnusrso** [comment]
thank you,i have see it.
