### ISSUE TITLE
How to disable Cache ? 

### ISSUE THREAD

**Issue by RamyarIran** [scriptPilot/app-framework#651]
Hey :) thanks for this perfect minimal framework.
Everything works well except cache! When I use `npm run dev` it open the app in browser but with a strength cache! I have to open in in incognito mode and close and open it after every update! any idea how to fix it ? 

Thanks

**Comment by capgros** [comment]
What you can do, with google chrome, is opening Developer Tools (F12) and in Application Tab checking the "clear storage" - "clear site data" options. 
![image](https://user-images.githubusercontent.com/12518582/29918892-874c20f2-8e47-11e7-9347-a6f651f57706.png)

**Comment by RamyarIran** [comment]
Easier life to me know (y)
