### ISSUE TITLE
Kitchen Sink with using Vue components instead of HTML?

### ISSUE THREAD

**Issue by JPBuenaventura** [scriptPilot/app-framework#658]
Is there a kitchen sink version using actual Vue components?

I looked into the official Framework-Vue repo and found out some of the components were not included (e.g. DatePicker, etc).

Thank you!

**Comment by scriptPilot** [comment]
@JPBuenaventura - The F7-Vue kitchen sink does not cover every F7 functionality in its kitchen sink, but should be possible to get the result with the docs. DatePicker should be integrated in the form elements in their kitchen sink. App Framework demo uses the F7 kitchen sinks.
