### ISSUE TITLE
State still restoring after disabling restoreComponentData and restoreHistory

### ISSUE THREAD

**Issue by JPBuenaventura** [scriptPilot/app-framework#661]
Hi scriptPilot/Team,

I dunno if I'm doing it right. I set both restoreComponentData and restoreHistory to false but app state is still being restored every time app is opened.

Is this the correct approach?

Thanks.

**Comment by scriptPilot** [comment]
@JPBuenaventura - What exactly do you mean by "state" ?

**Comment by JPBuenaventura** [comment]
I just want the framework to always load a default page instead of loading the previously accessed pages.

**Comment by rastapastaman** [comment]
Nice

**Comment by scriptPilot** [comment]
Currently, at minimum the last page will be restored. If you want to load always the default pages, you have to make a workaround, at it is not the common behavior. Details to the state restoration: https://github.com/scriptPilot/app-framework/blob/master/docs/state-restoration.md

**Comment by josteph** [comment]
Any workaround about this issue?

**Comment by patrickpissurno** [comment]
This is really annoying. "... at it is not the common behaviour"? Sure it is the common behaviour. How can I check something server-side before choosing which page I should load without a "proxy" page? I think you should take a newer look at this issue, as it's really important for some people (like me). In the mean time, I'll try to find some workaround in your code. State restoration is good to have (and you did a great job doing it automatically for us), but for lots of apps, it needs to be done manually.

**Comment by scriptPilot** [comment]
Good workaround @patrickpissurno, thank you!

**Comment by tiptronic** [comment]
I think a flag to set this option would be a good addition to the config file, no?

**Comment by scriptPilot** [comment]
Created a new issue for follow-up:
https://github.com/scriptPilot/app-framework/issues/773
