### ISSUE TITLE
Cordova compiling

### ISSUE THREAD

**Issue by JPBuenaventura** [scriptPilot/app-framework#662]
Are these the steps performed when compiling an APK?
> Prepare webpack & other framework7 related stuff
> Download cordova plugins
> Compile cordova
> Delete cordova generated files and directories (index.html, www, etc.)
> Launch APK using default emulator

I've added 2 plugins to cordova and every time i run "npm run android" the plugins are being downloaded.

Currently I'm looking at the browser-sync cordova plugin but if generated files under /node_modules/cordova/bin are always deleted, there'll be no files to watch.

I find it hard to test using an actual device for the native functions. Do we an alternative?

Thanks

**Comment by scriptPilot** [comment]
That is how the design works currently. Feel free to propose a better one :-)

**Comment by outluch** [comment]
Impossible to test on device or even with emulator. Every plugin downloaded every time. Weird..

**Comment by juanpintom** [comment]
It would be good an option where the plugins aren't updated automatically. 

Really thanks for your work scriptPilot, app-framework it's really good! :P
