### ISSUE TITLE
FTP deployment is not working in Windows 10

### ISSUE THREAD

**Issue by capgros** [scriptPilot/app-framework#665]
Hi,
I'm using windows 10. Npm run ftp never worked. It states 'Failed to connect to the FTP server'

I can connect to the ftp server with my usual client.

Thank you for your help!

**Comment by scriptPilot** [comment]
Just tested on Windows 10 Professional - no issues. Please let me know if you have still issues.

**Comment by capgros** [comment]
I will try again and update info
