### ISSUE TITLE
"Failed to read language files" error

### ISSUE THREAD

**Issue by edgegfx** [scriptPilot/app-framework#667]
Hey everyone,

Just got this installed and am trying to run "npm run major", but getting this error every time. The language files still have the default keys and I'm not aware anything is locking those files. Any ideas?

Thank you!

**Comment by capgros** [comment]
Can you provide some info of your environment? Windows 10? Linux? 
Using some tool or from terminal?

**Comment by edgegfx** [comment]
I'm on OS X 10.12 running Node 8.5.0. I just installed iTerm and re-installed the files again. It seems to have compiled this time, oddly. I'm not sure what changed as I re-installed the files several times yesterday!

I'll keep an eye and post if it appears to break again. Thanks.

**Comment by siyamak45** [comment]
I have the same problem. I'm on OS X 10.10.5 running Node 8.5.0. aslo I use brackets for file editing.

**Comment by charlextra** [comment]
I have the same problem when I run the command npm run android.I am blocked.What could be the solution of this problem.Thank you in advance.Je suis sur windows 10.La version de mon node est v8.9.1
