### ISSUE TITLE
Vue.set(object, key, index)

### ISSUE THREAD

**Issue by capgros** [scriptPilot/app-framework#670]
Does somebody know how to acces Vue.set from a method?

**Comment by VSymonenko** [comment]
`methods: {
  	setWithAPI () {
    	this.$set(app, 'msj', 'world!')
    }
  }`

look this example [jsfiddle](https://jsfiddle.net/simati/dxojxq00/3/l)

If you use  **vuex** try `this.$set(this.app, 'msj', 'world!')` where **this.app** is a [getter](https://vuex.vuejs.org/en/getters.html)

**Comment by capgros** [comment]
Worked!

Don't really know how to use Vuex with app framework.
