### ISSUE TITLE
Firebase configuration / window.db use

### ISSUE THREAD

**Issue by lukedj78** [scriptPilot/app-framework#671]
I'm trying for the first time to use app-framework following the documentation,
I have configured firebase in the config file but when I run the app and try to invoke the database using window.db I receive an error message "window.db is not a function".
Firebase is already initialized and ready to use or I need to make further configurations?
thank you

**Comment by ktong88** [comment]
i am also having issue with firebase when trying to use facebook login. It looks like window.firebase.auth.FacebookAuthProvider is undefined when i check it through console log

**Comment by lukedj78** [comment]
I think the problem is that the firebase instance is not initialized but I do not know why

**Comment by scriptPilot** [comment]
@lukedj78 , @ktong88 - At which point do you try to access window.db ?
It should be generated after Framework7 / Vue, so in any created / mounted hook or later.

**Comment by lukedj78** [comment]
I tried to follow the dame code in the demo app! I called the database in monted method but in console I get the error window.db is not defined

**Comment by ktong88** [comment]
i am actually try to access firebase instance in the demo app (kitchen-sink-ios.js)

  myApp.onPageInit('login-screen-embedded', function(page) {
    $$(page.container).find('.list-button').on('click', function() {
      var username = $$(page.container).find('input[name="username"]').val();
      var password = $$(page.container).find('input[name="password"]').val();
      window.firebase.auth().signInWithEmailAndPassword(email, password) **// this is working**
      var provider = new firebase.auth.FacebookAuthProvider(); **// this is giving constructor error**
      window.firebase.auth().signInWithRedirect(provider);
      myApp.alert('Username: ' + username + ', password: ' + password, function() {
        mainView.router.back();
      });
    });
  });

**Comment by scriptPilot** [comment]
Maybe you have not allowed Facebook to be used in the Firebase console? I think it's more a Firebase related question.
