### ISSUE TITLE
Option to change body background color with phone frame / limited application size

### ISSUE THREAD

**Issue by gcshri** [scriptPilot/app-framework#679]
I am trying to create a fixed width desktop app with the framework and have set the following options:

````
  "iconBackgroundColor": "#eeeeee",

  "limitApplicationWidth": 1200,
  "limitApplicationHeight": "100%",
  "showPhoneFrameOnDesktop": false,
````

index.ejs in the node_modules/... folder has this but the color does not seem to change.

````
  <body style="background: <%= htmlWebpackPlugin.options.iconBackgroundColor %>">
````

The body is styled as follows when I run the dev server.

````
<body style="background: rgb(51, 51, 51);" class="limitWidth theme-indigo">
````

Also noticed that 'limitWidth/limtHeight' has the style 

````
.limitHeight, .limitWidth {
    background: #333333;
}
```` 

Am I missing something?

**Comment by scriptPilot** [comment]
@gcshri - Please can you specify your question and the steps you did / the expected result / the actual result - thanks.

**Comment by gcshri** [comment]
Sorry, should have added a screenshot. 

When I configure the app to have a fixed width on the desktop using "limitApplicationWidth" in the config.json, how would I change the background color. Currently fixed in the body tag as mentioned above.


![screen shot 2017-10-27 at 4 19 29 pm](https://user-images.githubusercontent.com/14210493/32094726-5ab2a50c-bb33-11e7-9d2a-f5355a48b3bc.png)

**Comment by scriptPilot** [comment]
OK, now I've got that point - I will add a configuration option to make it clean.
