### ISSUE TITLE
Firebase logout

### ISSUE THREAD

**Issue by princewolf** [scriptPilot/app-framework#680]
Require simple way to call Firebase logout screen after a user has been logged in

**Comment by scriptPilot** [comment]
@princewolf - Please can you specify your question?

**Comment by princewolf** [comment]
Sorry I couldn't find out in the documentation about logging users out after login. After I checked through the demo source code, I managed to find out how to do so. Thank you.

**Comment by scriptPilot** [comment]
Reopened in order to improve the docs.

**Comment by scriptPilot** [comment]
@princewolf - Here you find a way how to realize it very simple :-)

https://github.com/scriptPilot/app-framework/blob/master/docs/firebase.md
