### ISSUE TITLE
Push notification and charting

### ISSUE THREAD

**Issue by princewolf** [scriptPilot/app-framework#684]
It would be great to have some ways to perform push notification for apps developed with the App Framework. It will increase users engagement too. 

Another component that might be good to have is integration with ChartJS or any other JS charting for displaying at least line, bar, pie and area charts.

**Comment by scriptPilot** [comment]
Hey, both already to be found in the issues:

https://github.com/scriptPilot/app-framework/issues/641

https://github.com/scriptPilot/app-framework/issues/94
