### ISSUE TITLE
Login popup component error

### ISSUE THREAD

**Issue by teddy-dubal** [scriptPilot/app-framework#693]
Hi , 
The login-popup component create an error console.

![capture du 2017-10-29 15-58-07](https://user-images.githubusercontent.com/7427796/32145043-7c6f81a2-bcc2-11e7-8a8a-168ca3b01e67.png)

the data-page attribute is null

![capture du 2017-10-29 15-58-35](https://user-images.githubusercontent.com/7427796/32145055-a17bd1bc-bcc2-11e7-9c6c-a47ff50865e1.png)

My workaround 

![capture du 2017-10-29 16-00-17](https://user-images.githubusercontent.com/7427796/32145064-bd510e66-bcc2-11e7-8176-abb42b5afb36.png)

**Comment by scriptPilot** [comment]
@teddy-dubal - Thank you, fix released!
