### ISSUE TITLE
Question: Adding App-Framework to new vue project

### ISSUE THREAD

**Issue by gcshri** [scriptPilot/app-framework#695]
Noticed that the vue and other components in the framework are rather old.

Is it possible to create a new Vue project using a simple or webpack template and adding the framework to it? Have some requirements which need a newer vue / firebase version.

Seems like the framework is locked to older versions.

Thanks

**Comment by scriptPilot** [comment]
No, that is not possible as App Framework has to be tested together with all components. But I've seen there happend a lot on Vue.js site, I opened an issue to update Vue - https://github.com/scriptPilot/app-framework/issues/696
