### ISSUE TITLE
Upload on ftp on a subfolder

### ISSUE THREAD

**Issue by Pitouli** [scriptPilot/app-framework#697]
Hello, 

The ftp function works well, but I have an issue: I would like to put the files in the folder /www/myapp/
(so I would access my app from http://mywebsite.com/myapp/)

Currently it uploads the files in the root folder, so I cannot access it at all from the web (and if it was uploaded in the /www/ folder, it would be an issue too since I've got other websites in the same server)

Is there a way to support this that I didn't find? Could it be added to the next version?

Thanks!

**Comment by scriptPilot** [comment]
Consider it as enhancement.

Workaround: Create a dedicated FTP user for that directory ;-)

**Comment by Pitouli** [comment]
For the workaround, I do not have the required rights to do so! :) 

But I'll try to update the script, and if I succeed, I'll do a PR.

**Comment by scriptPilot** [comment]
@Pitouli - Possible in V3 :-)
