### ISSUE TITLE
scrolling not work in android default browser

### ISSUE THREAD

**Issue by davisbra** [scriptPilot/app-framework#699]
hi
scrolling not work in android default browser and android webview

**Comment by scriptPilot** [comment]
Hey @davisbra - do you have a sample repo to reproduce that behavior? For me it works fine.

**Comment by davisbra** [comment]
I test your demo app (https://demo.app-framework.com/)in Samsung galaxy A5 default browser ( not chrome or other browser) and HTC one M7  default browser not scrolling(scrolling down) in any pages of demo app.
(in chrome browser it works fine)

**Comment by scriptPilot** [comment]
@davisbra - OK, at the moment I am not sure if it's related to F7 or AF. Please can you test with the same browser the demo of Framework7.io? Maybe with V1 if possible.

**Comment by mobsted** [comment]
We solved it like that.
In node_modules/app-framework/client/app.js 
here

```
mixins.preventOverscroll = {
  created: function () {
    // No native application (Overscroll disallowed by Cordova for native Apps)
    if (!window.cordova) {

```
replace with 


```
var iOS = !!navigator.platform && /iPad|iPhone|iPod/.test(navigator.platform)
mixins.preventOverscroll = {
  created: function () {
    // No native application (Overscroll disallowed by Cordova for native Apps)
    if (!window.cordova && iOS) {
```

**Comment by scriptPilot** [comment]
Should be fixed in V3, if not, please open a new issue.
