### ISSUE TITLE
Framework7 IOS/Material theme CSS is appended to head of document after components CSS

### ISSUE THREAD

**Issue by ryanmstokes** [scriptPilot/app-framework#708]
It is not possible to overwrite Framework7 CSS classes as the Framework7 theme css is appended to the head of the document after any custom CSS declared within components.

<img width="893" alt="screen shot 2017-11-01 at 17 32 50" src="https://user-images.githubusercontent.com/4103619/32285500-c483e072-bf2a-11e7-8425-1d1adc793c09.png">

Here you can see that I have written a class to overwrite the behaviour of this class:

    @media (min-width: 768px){
        .tabbar a.tab-link, .tabbar a.link {
            width: auto;
            min-width: 105px;
        }
    }

but its not possible as it appended before the frameworks theme CSS and so is overwritten.

Can you point me in the right direction as to how load the frameworks css first before any additional css I have written in components?

Many Thanks!

**Comment by scriptPilot** [comment]
OK, wrong order in my eyes - recognized as a bug.

**Comment by scriptPilot** [comment]
OK, seems the issue is well known ...

https://github.com/webpack/webpack/issues/215
https://github.com/babel/babel/issues/2061
https://github.com/webpack/webpack/issues/1343
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200

etc.

**Comment by littlegreening** [comment]
@ryanmstokes, @scriptPilot 

I solved this by add beneath code after app.js#L708
https://github.com/scriptPilot/app-framework/blob/e7ea070d6e21d61e0b781f6c57b536e5fa2ec50d/client/app.js#L708

```
beforeCreate: function () {
    this.theme = window.localStorage.theme ? window.localStorage.theme : this.config.theme.split('-')[0]
    if (process.env.NODE_ENV === 'development') {
      if (this.theme === 'ios') require('./ios')
      else require('./material')
    } else {
      window.Dom7('link').each((i, el) => {
        let href = window.Dom7(el).attr('href').match(/^(ios|material)\.(.+)\.css$/)
        if (href !== null && href[1] !== newTheme) {
          window.Dom7(el).remove()
        }
      })
      window.Dom7('script').each(function (i, el) {
        let src = window.Dom7(el).attr('src').match(/^(ios|material)\.(.+)\.js$/)
        if (src !== null && src[1] !== newTheme) {
          window.Dom7(el).remove()
        }
      })
    }
  }
```
Additionally, if you want to change the order of icon and framework CSS file, you can change mixins code `loadIconFonts` after `manageTheme`.

Hope it helps. ：）

**Comment by scriptPilot** [comment]
In V3, the order is ok:
- default F7
- icon fonts
- app.css
- app module / page module css
