### ISSUE TITLE
Changing the “devServerPort” setting in Docker is not valid

### ISSUE THREAD

**Issue by crcms** [scriptPilot/app-framework#710]
When I set the `devServerPort` option in the Docker development environment and then run npm run dev, the `app / config.json` file always changes` devServerPort` to 8080, but I can use it in the local environment.

Node version number: v6.11.5

Npm version number: 3.10.10

Ubuntu version number: 16.04

**Comment by scriptPilot** [comment]
Hey, what do you mean with Docker development environment?

**Comment by crcms** [comment]
Hello, I downloaded a docker image of ubuntu16.04 and built a nodejs + npm environment myself, opened a mapping port and mounted a container volume,
`docker run -itd --name crcms-node -p 28080: 28080 -v ~ / javascript: / data crcms / ubuntu: node bash`, but after I changed the `devServerPort` port in docker, the port was automatically Change back to `8080`

**Comment by scriptPilot** [comment]
@crcms - OK, thanks - have to do further investigations on it.

**Comment by scriptPilot** [comment]
@crcms - The dev port can be configured in V3 :-)
