### ISSUE TITLE
Failed to remove files in Cordova folder

### ISSUE THREAD

**Issue by crcms** [scriptPilot/app-framework#712]
Hello, I am running npm run android, every time it fails, the console always reminds the following statement:

Error: Failed to remove files in Cordova folder.

Please open an incident on GitHub:
https://github.com/scriptPilot/app-framework/issues

At first I thought it was an environmental issue, but I tried in Windows, Ubuntu, the results are the same, but can not be updated accurate error message, Android skd, Android Studio, have been successfully configured

I have tried many times and the result is the same, I hope to get your help, I am very grateful

**Comment by scriptPilot** [comment]
@crcms - I've added some debugging to that script. Please can you enable debug mode in the app config file (debug: true), run the script and post the content of the debug.log file - it will be created in the project folder. Thanks!

**Comment by scriptPilot** [comment]
No more error in V3 ... hopefully
