### ISSUE TITLE
Error app-framework@1.19.1

### ISSUE THREAD

**Issue by strevecloud** [scriptPilot/app-framework#715]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "G:\\development\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:eslint"
npm ERR! node v6.11.4
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! development@1.0.6 test:eslint: `node node_modules/app-framework/scripts/testESLint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the development@1.0.6 test:eslint script 'node node_modules/app-framework/scripts/testESLint'.
npm ERR! This is most likely a problem with the development package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/app-framework/scripts/testESLint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs development
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls development
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\development\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "G:\\development\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.11.4
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! development@1.0.6 test: `npm run test:eslint && npm run test:config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the development@1.0.6 test script 'npm run test:eslint && npm run test:config'.
npm ERR! This is most likely a problem with the development package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test:eslint && npm run test:config
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs development
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls development
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\development\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "G:\\development\\node_modules\\npm\\bin\\npm-cli.js" "run" "update"npm ERR! node v6.11.4
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
npm ERR! development@1.0.6 update: `npm run test && npm run update:npm && npm run update:eslint && npm run update:editorconfig && npm run update:ignore`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the development@1.0.6 update script 'npm run test && npm run update:npm && npm run update:eslint && npm run update:editorconfig && npm run update:ignore'.
npm ERR! This is most likely a problem with the development package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test && npm run update:npm && npm run update:eslint && npm run update:editorconfig && npm run update:ignore
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs development
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls development
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\development\npm-debug.log

**Comment by scriptPilot** [comment]
@strevecloud - Please update to 1.19.2 - is a rollback to 1.18.2 - should be fixed then.

Dennis

**Comment by strevecloud** [comment]
thanks 👍
