### ISSUE TITLE
[Question] Bug framework7-Vue Back link

### ISSUE THREAD

**Issue by teddy-dubal** [scriptPilot/app-framework#730]
Hi , do you notice this bug on framework7-vue , after 2 levels of navigation button back don't work when domcache is set to false
 
i open an issue
https://github.com/framework7io/Framework7-Vue/issues/282

**Comment by meteozond** [comment]
Looks like it is normal behaviour. Built in back action is tight linked with dom/page cache. If you disabling it you have to provide your own previous page detection algorithm.
