### ISSUE TITLE
Configurable splashscreen (different from app icon)

### ISSUE THREAD

**Issue by webmass** [scriptPilot/app-framework#736]
Hi,

The splashscreen should be configurable to be different from the app icon, indeed most apps use splashcreens different from their app icon.

Best regards

**Comment by scriptPilot** [comment]
Hey webmass, you can use preroutes to use your own splash screen pages .... solution for you?
https://github.com/scriptPilot/app-framework/blob/master/docs/setup.md

**Comment by webmass** [comment]
Hi,

I should have been more precise ;), I'm talking about the native iOS / android splashscreen

The process would be the same as icon.png (creating different sizes, filling in config.xml, etc) but it would use splash.png instead (if it exists)

**Comment by scriptPilot** [comment]
OK, reopened as feature request :-)

**Comment by scriptPilot** [comment]
@webmass - Will be possible with V3 soon
