### ISSUE TITLE
How to configure multiple app.vue?

### ISSUE THREAD

**Issue by JCKodel** [scriptPilot/app-framework#737]
I'm writing a number of mini-apps that will be loaded in different contexts (imagine a plain HTML in an iFrame that will load another url with an AppFramework app, with its own navigation and isolated from the other mini-apps).

Routing doesn't seem to work (it will always load the home page, then animating to the desired page when pushState:true).

I don't know if this is an AppFramework or f7vue issue =\

**Comment by scriptPilot** [comment]
Mhm ... Its more related to Framework7 / Framework7-Vue I would say. You can set parameters to avoid the transitions.
