### ISSUE TITLE
Hang in Swiper Slider > Multiple per page

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#739]
If I chose this demo, and slide 2 or 3 sliders, the app hangs alltogether and (mostly) needs to get force-quitted (one or more times, as it always tries to recover to the last state).

Can repro 100% on iPhone X iOS 11.1.2

**Comment by tiptronic** [comment]
After some more investigation, it seems it is not caused by 'multiple sliders' (although it is noticable, if I swipe the very first slider 4 times, it has a short 'hickup' and tries to load something (and sometimes hangs there - not sure why, since I have a stable and fast WLAN here).

Is the demo-project open-sourced somewhere? (would help to see what's going on.)

**Comment by scriptPilot** [comment]
Hey @tiptronic - do you think it's related to App Framework or more to Framework7 itself?

**Comment by tiptronic** [comment]
I think it is both... but just a logical problem. If the app hangs at a point of no return, it always try to start there again, which brings you back to the same point of no return ;)

**Comment by scriptPilot** [comment]
@tiptronic - OK, I have to investigate in detail.

**Comment by scriptPilot** [comment]
@tiptronic - In V3 with Framework7 3 it seems fixed :-)
