### ISSUE TITLE
TypeError: Cannot read property 'app-framework' of undefined

### ISSUE THREAD

**Issue by Danial-Alh** [scriptPilot/app-framework#740]
Hello,

I'm a beginner and trying to install 'app-framework' via 'npm install app-framework'; but I get following error:

> \> node scripts/postinstall
> 
> D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\app-framework\scripts\postinstall.js:128
>   if (env.pkg.devDependencies['app-framework'] === '*') {
>                              ^
> 
> TypeError: Cannot read property 'app-framework' of undefined
>     at createSnapshot (D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\app-framework\scripts\postinstall.js:128:30)
>     at completePackageJson (D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\app-framework\scripts\postinstall.js:156:3)
>     at completePackageJson (D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\app-framework\scripts\postinstall.js:151:3)
>     at Object.<anonymous> (D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\app-framework\scripts\postinstall.js:155:1)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.runMain (module.js:590:10)

> 
> npm WARN Error: EPERM: operation not permitted, scandir 'D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\readline2\node_modules'
> npm WARN     at Error (native)
> npm WARN  { Error: EPERM: operation not permitted, scandir 'D:\Learnings\SelfProjects\TheFirstAppFramwork\node_modules\readline2\node_modules'
> npm WARN     at Error (native)
> npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\Learnings\\SelfProjects\\TheFirstAppFramwork\\node_modules\\readline2\\node_modules\'\n    at Error (native)',
> npm WARN   errno: -4048,
> npm WARN   code: 'EPERM',
> npm WARN   syscall: 'scandir',
> npm WARN   path: 'D:\\Learnings\\SelfProjects\\TheFirstAppFramwork\\node_modules\\readline2\\node_modules' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! app-framework@1.19.4 postinstall: `node scripts/postinstall`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the app-framework@1.19.4 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I've searched a bit but didn't get any solutions.

Thanks for your helping

**Comment by scriptPilot** [comment]
Please let me know the steps you've done to reproduce the error ... looks the installation guide was not followed step by step?

https://github.com/scriptPilot/app-framework/blob/master/docs/setup.md
