### ISSUE TITLE
Update framework7-vue to v0.9.4

### ISSUE THREAD

**Issue by meteozond** [scriptPilot/app-framework#743]
Please. There is a very important fix of totally broken `f7-popup` in f7vue 0.9.4.

I've already tried `f7vue-update` script but after passing through the `dev` and `installed` mode checks finally got  **Framework7-Vue build process failed** with either git and packaged versions.

Looking through `f7vue-install` makes me thinking that is unusable too due to lots of commented/disabled code.

**Comment by scriptPilot** [comment]
Done in next release - please see here how to do it manually if required:
https://github.com/scriptPilot/app-framework/blob/master/docs/dev-update-vendor-folder.md
