### ISSUE TITLE
not working in android webview

### ISSUE THREAD

**Issue by davisbra** [scriptPilot/app-framework#745]
when I add your url to android webview it not working and stop in app initializing page with the following errors:
The key "minimal-ui" is not recognized and ignored.demo.app-framework.com/:1
Uncaught TypeError: Object #<HTMLDivElement> has no method 'append' init.40ef6af.js:1
Uncaught ReferenceError: ExtendableEvent is not defined /offline-service-worker.js:3
Uncaught TypeError: Cannot read property 'theme' of null app.40ef6af.js:44
how to fix it?
my code : 
`super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        WebView webView = (WebView) findViewById(R.id.webview);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebContentsDebuggingEnabled(true);

        webView.getSettings().setAllowFileAccess(true);
        webView.getSettings().setPluginState(WebSettings.PluginState.ON);
        webView.getSettings().setDatabaseEnabled(true);
        String databasePath = this.getApplicationContext().getDir("database",
                Context.MODE_PRIVATE).getPath();
        webView.getSettings().setDatabasePath(databasePath);
        webView.setWebChromeClient(new WebChromeClient() {
            @Override
            public void onExceededDatabaseQuota(String url, String databaseIdentifier, long currentQuota, long estimatedSize,
                                                long totalUsedQuota, WebStorage.QuotaUpdater quotaUpdater) {
                quotaUpdater.updateQuota(estimatedSize * 2);
            }
        });
        webView.loadUrl("https://demo.app-framework.com/");`

**Comment by scriptPilot** [comment]
Which module do you use, what do you try to archive?
