### ISSUE TITLE
What is layout: dark supposed to do?

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#746]
What is the 'layout' key supposed to do?
I tried default, white, dark, but couldn't detect any change (no matter if theme is ios, material or something else).

**Comment by scriptPilot** [comment]
Find here more details:
https://github.com/scriptPilot/app-framework/blob/master/docs/application-style.md

**Comment by tiptronic** [comment]
I was referring to the setting, which basically does nothing if set in the config file.

The problem seems, that currently documentation and code are out-of-sync - so better to have a look at it, when everything is on v2.

**Comment by scriptPilot** [comment]
@tiptronic , I updated the documentation links all over in App Framework7 docs.

Does this helps you?
http://v1.framework7.io/docs/color-themes.html

**Comment by tiptronic** [comment]
@scriptPilot No - it doesn't really help, but I understand what it is supposed to do ;). 
The reason is: some/most options in the config file included in app-framework don't do anything in the sample app (kitchensink), because they're overwritten by kitchensink obviously...

**Comment by scriptPilot** [comment]
Ah, year the kitchen sink has some additional CSS.
But if you use a clean installation, it should work.
Please let me know :-)

**Comment by tiptronic** [comment]
@ehausen If you tried with kitchen-sink, you tapped into the same issue... the config is overwritten by kitchen-sink. I guess when starting a fresh project it works

**Comment by ehausen** [comment]
The documentation, v1 and 
http://framework7.io/docs/color-themes.html

say that it should be
`<div class="page theme-dark">` 
but it does *not work*

this works:
`<div class="page" layout="dark">`

**Comment by ehausen** [comment]
Solved!

The values are stored quite persistently in browser local storage.

To clear (in Google Chrome or similar) you can:
- Right click.. Inspect --> Opens dev tools
- Click "Application" Tab
- Select Storage > Local Storage > localhost:8080
- Find icon that looks like forbidden sign (clear all) and click it to clear values

**Comment by scriptPilot** [comment]
Explanations for upcoming Framework7 / App Framework 3 here:
https://framework7.io/vue/colors.html
