### ISSUE TITLE
Dynamic "login" properties in routes.json

### ISSUE THREAD

**Issue by josteph** [scriptPilot/app-framework#747]
Hello, thanks for the great framework!

I noticed that whenever I open the app, it will automatically redirect me to `/index` page if I don't set properties `"login": true` in the route.json file.

So let's say I want to integrate another login method (maybe like facebook, google, etc..), how do I change during runtime the variable login set in the routes.json so that I am able to redirect to `/index` ?

**Comment by scriptPilot** [comment]
You can edit the Vue root object to add your own preroute:
https://github.com/scriptPilot/app-framework/blob/master/docs/extend-vue-root-object.md

**Comment by josteph** [comment]
Thanks for your reply. Will this solve the issue about redirecting to the last page when opened again?
I had to use `login` routes instead of `login-popup` in my project, that's why.

**Comment by scriptPilot** [comment]
@josteph - No, it doesn't. For that I opened a feature request:
https://github.com/scriptPilot/app-framework/issues/766
