### ISSUE TITLE
Is this project already dead?

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#748]
Sorry to ask, but there was no progress recently, no questions answered, no issues commented, no contact available.... 

So my simple question is: is this project something to build on, or was it just a quick test?

I'm new to f7, so please bear with me if I'm completely wrong - but it would have been a great starting-point (or even 'is').

andy

**Comment by scriptPilot** [comment]
Hey Andy, in fact I have current some other prios as we move to another city and we have to prepare everything for our baby. In addition, we expect Framework 2 to habe some update / simplification of the framework. So, there is a future and a more or less robust framework you can use :-)

**Comment by tiptronic** [comment]
Hi @scriptPilot , 
thx for the reply - good to hear - and good luck with your baby!!
I am just starting with F7, and checking my options... so app-framework seems to be a good real-world starting point, although some things didn't work as expected. But as I found out in the meantime, the F7 on GitHub is v2 already, but the documentation is still v1... So hopefully the move to v2 is done soon, to get me not even more confused 😉 
Cheers

**Comment by Pitouli** [comment]
Congrats for your baby! :)

App-Framework works very well, but I really need Cloud Firestore, and I would like to switch soon on F7 v2 while my project is not too big.

The question is: you said "there is a future", but do you have any idea in which timeframe? :) 

Thanks a lot for all the work done!

**Comment by scriptPilot** [comment]
@tiptronic @Pitouli - Thanks, the baby is planned in next month :)

And this baby ... well ... I cannot give a time frame, but suggestions and commitments to a good v2 are appreciated. Let me know your ideas. Best way - per topic one issue.

The docs are updated now with correct links to Framework7/Vue V1.
