### ISSUE TITLE
Question: Where to save global data

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#750]
Hi & sorry: noob-question 😉

how do I save globally available data in app-framework?

Let's say I have a couple of static variables and/or instance variables to which I need access from multiple (or all) components. Where do I define those variables properly in app-framework?

thx

andy

**Comment by capgros** [comment]
There's a global data object with really easy acces:
It's well documented here: [https://github.com/scriptPilot/app-framework/blob/master/docs/data-object.md](https://github.com/scriptPilot/app-framework/blob/master/docs/data-object.md)

**Comment by tiptronic** [comment]
Thanks - that works, but it's not very flexible.
E.g. if I have a long array:
```javascript
this.$db('longarray', longarray)
```
I have no access to the array's elements, except keeping a copy. 
Also I cannot push/pull to/from the array, without getting it first.

So for the time being, I am saving a reference to a component in $root, so I am able to manipulate the components data from elsewhere:

In the component (simplified):
``` javascript
this.$root.$data['myComponent'] = this;
...
```
and then when I need to manipulate it's data (in $root):
```javascript
this.myComponent.componentData = longArray;
this.myComponent.componentData.push("new item");
...
```
I'm pretty sure, that's not as intended, but I haven't found a better way to accomplish this (instead using a store or something, which is not really what I'm looking for). 
I need this kind of functionality e.g. for cases, where e.g. lots of users join/leave a chatroom or lots of (IoT-) devices send messages in a very short frequency and those informations update a list.

Any hint appreciated...

**Comment by scriptPilot** [comment]
You can use Vuex (https://github.com/scriptPilot/app-framework/blob/master/docs/extend-vue-root-object.md) or call the array with main.sub.path ... element

**Comment by tiptronic** [comment]
What do you mean by 'main.sub.path' element?

For now, I am using my own bus, which does what I want... I think it's just the way we look at our data. While the Vue-way (props down, events up) is ok in most of the cases, there are still edge-cases where I need more flexibility.

I will stick with it for now and look at it at a later point.
Thx for taking the time to answer & happy new year1

**Comment by scriptPilot** [comment]
That mean you can address the object

```
{
  "main": {
    "sub": {
       "key": "value"
    }
  } 
}
```
with `$db('main.sub.key', 'value')` - clear now?

**Comment by tiptronic** [comment]
Jep - thanks for clarification...

**Comment by scriptPilot** [comment]
OK, added that to the docs.

https://github.com/scriptPilot/app-framework/blob/master/docs/data-object.md#with-app-framework-v1132-or-later
