### ISSUE TITLE
webpack dev server can't get RSS-feeds due to CORS settings

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#759]
If I run npm run dev, I can't download external resources, e.g. rss-feeds due to access control checks.
Error is e.g.:
```
Failed to load resource: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.
```
when building using ```npm run minor``` everything works fine. 
I think this is due to some setting in the devServer, but I don't know where to change that...

**Comment by scriptPilot** [comment]
Looks like not linked to App Framework itself ... what says Google?

**Comment by tiptronic** [comment]
google says 'devServer' needs to send the correct CORS headers... but I couldn't find where the 'devServer' is :/

**Comment by scriptPilot** [comment]
@tiptronic - OK, I have to do deeper investigation here.

**Comment by scriptPilot** [comment]
@tiptronic - If there is still an issue with V3 (probably), please open a new issue to follow-up how to configure the right way F7 + Parcel Bundler.
