### ISSUE TITLE
It is difficult to extend this framework.

### ISSUE THREAD

**Issue by xerosanyam** [scriptPilot/app-framework#760]
Can anyone guide me on
1. How can I write my service workers
2. How can I include more firebase services

**Comment by scriptPilot** [comment]
Did you check the docs how to include own modules to App Framework?

**Comment by Pitouli** [comment]
@xerosanyam I do not know if I did it the right way, but I did t a way that works. I added the support of Firestore.

You can have a look here: 
https://github.com/scriptPilot/app-framework/compare/master...Pitouli:master

It list all the changes I made between my forw and the original, and they are mostly (if not exclusively) about adding Firestore.

You can ignore all the "build/" files.

**Comment by scriptPilot** [comment]
@Pitouli - Thank you for that as workaround for users.

Added as feature request: https://github.com/scriptPilot/app-framework/issues/751

**Comment by xerosanyam** [comment]
@scriptPilot I did check the docs. But they mention extending Vue component. What I am looking for are service workers and firebase services.
@Pitouli Thank you for a head start! :+1:

**Comment by scriptPilot** [comment]
@xerosanyam - OK, but correct me if I am wrong, but you can add service workers for example in the app.vue file ... eg in the created hook:

```
created() {
  ... service worker implementation
}
```

https://developers.google.com/web/fundamentals/primers/service-workers/

**Comment by xerosanyam** [comment]
Cool. I'll try that. Thanks @scriptPilot.
