### ISSUE TITLE
Framework7 v2 Update?

### ISSUE THREAD

**Issue by josteph** [scriptPilot/app-framework#761]
When do you plan to update the framework dependency?

Framework7 v2 just recently released and many methods are to be replaced. It is hard to keep using v1 syntax since the official documentation is in v2 already.

Thanks.

**Comment by scriptPilot** [comment]
Hey! As there is currently no documentation available for V2, for now, App Framework keeps the version 1. But v2 should be the future!

**Comment by josteph** [comment]
[Framework7-Vue 2](https://github.com/framework7io/framework7-vue/commit/2f0632c89101598171084d5f758fda87c9c371bd) stable version just recently released!

**Comment by scriptPilot** [comment]
@josteph - You are right, but still, there is no updated documentation available.

**Comment by josteph** [comment]
@scriptPilot Correct.. really need this for my next release too.

**Comment by scriptPilot** [comment]
@josteph - I understand you want to have all the new features asap available, but please keep in mind it's all open source and a hobby. So, if you really "need" something, feel free to push by paying or support the development :-)

**Comment by josteph** [comment]
@scriptPilot Yup, for sure will do, thanks a lot.

**Comment by tiptronic** [comment]
@scriptPilot Jep - just drop a note to where to send some money!

**Comment by scriptPilot** [comment]
For which amount I have to ask my manager to create an account for? ;-)

**Comment by tiptronic** [comment]
If you don't have an account, I can send some bread, milk and Pampers instead 😉

**Comment by scriptPilot** [comment]
Next version will use Framework7 V3
#803
