### ISSUE TITLE
Error: Failed to empty build folder in cache

### ISSUE THREAD

**Issue by semvgelooven** [scriptPilot/app-framework#764]
Whenever I try the command:  npm run ios

I get the error 'Error: Failed to create Cordova project folder.' Xcode is installed, simulators tested and they run. Is this a directory permission issue?

EDIT: I removed the node_modules and reinstalled. Now I get the message 'Failed to empty build folder in cache'

EDIT: Changed the permissions of the 'node_modules' folder and problem seems solved.

**Comment by scriptPilot** [comment]
Thank for the update, good for other to now maybe.
