### ISSUE TITLE
Use variables for Cordova plugins

### ISSUE THREAD

**Issue by semvgelooven** [scriptPilot/app-framework#767]
I want to use the Camera Plugin (https://cordova.apache.org/docs/en/7.x/reference/cordova-plugin-camera/index.html)

Since iOS10 it's mandatory to include a reason to access the camera otherwise the app crashes. Normally I would add the following to my config.xml inside my Cordova based project.

`<plugin name="cordova-plugin-camera" spec="^2.4.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="insert description here" />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="insert description here" />
    </plugin>`

I know I can add this directly inside the info.plist but is there a way I can add these to the app-framework config.json?

**Comment by josteph** [comment]
Yes, it is possible by inserting in the `useCordovaPlugins` array:

`cordova-plugin-camera --variable CAMERA_USAGE_DESCRIPTION=Photo`

Basically this framework will execute `cordova plugin add ...` for each plugin(s) listed there.

**Comment by semvgelooven** [comment]
I see, good to know! Thanks.

**Comment by semvgelooven** [comment]
@josteph tried the above, but the values are not copied over to xcode.

**Comment by scriptPilot** [comment]
OK, need further investigation, I open it as feature request.

**Comment by scriptPilot** [comment]
In V3, you can edit the info.plist file manually. It will kept for later builds.
