### ISSUE TITLE
How to change html direction to RTL and LTR when a particular language is selected?

### ISSUE THREAD

**Issue by shajeeck** [scriptPilot/app-framework#768]
"app-framework" really looks very promising product, currently i am experimenting with it for a project.

I am new to framework7 and vuejs itself, coming from an angular and ionic background.

How can i change the direction of complete app from LTR to RLT when a particular language, say Arabic is selected in app-framework??

**Comment by scriptPilot** [comment]
Hey shajeeck, you have to

1) Enable it in the options

https://v1.framework7.io/docs/init-app.html

https://github.com/scriptPilot/app-framework/blob/master/docs/extend-vue-root-object.md#overwrite-framework7-options

2) Include the additional CSS files

https://v1.framework7.io/docs/rtl-layout.html
