### ISSUE TITLE
Is this.$db() equivalent to window.NativeStorage ?

### ISSUE THREAD

**Issue by josteph** [scriptPilot/app-framework#769]
Hello, I just want to make sure if doing `this.$db('main.sub', 'value')` is equal to `window.NativeStorage.setItem('main.sub', 'value')` ?

This is the [NativeStorage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage) plugin I mentioned. Seems like it is used in App Framework, so here I just want to confirm about the question above.

Thank you.

**Comment by scriptPilot** [comment]
More or less, details to be found in the code:
https://github.com/scriptPilot/app-framework/blob/master/client/app.js#L432

**Comment by josteph** [comment]
Ah, thanks for pointing the specific line!
