### ISSUE TITLE
Can't install any version on macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by patrickpissurno** [scriptPilot/app-framework#770]
Node Version: v8.9.1
NPM version: 5.6.0
App Framework version: latest (1.20.0) and previous (1.19.x)

Output:
```js
/Users/patrickpissurno/Documents/GitHub/my-app/node_modules/app-framework/scripts/postinstall.js:128
  if (env.pkg.devDependencies['app-framework'] === '*') {
                             ^

TypeError: Cannot read property 'app-framework' of undefined
    at createSnapshot (/Users/patrickpissurno/Documents/GitHub/my-app/node_modules/app-framework/scripts/postinstall.js:128:30)
    at completePackageJson (/Users/patrickpissurno/Documents/GitHub/my-app/node_modules/app-framework/scripts/postinstall.js:156:3)
    at completePackageJson (/Users/patrickpissurno/Documents/GitHub/my-app/node_modules/app-framework/scripts/postinstall.js:151:3)
    at Object.<anonymous> (/Users/patrickpissurno/Documents/GitHub/my-app/node_modules/app-framework/scripts/postinstall.js:155:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
npm WARN finance-bot@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-framework@1.20.0 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-framework@1.20.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrickpissurno/.npm/_logs/2018-01-17T18_06_27_648Z-debug.log
```

How to reproduce:
- Have macOS 10.13 installed
- Install Node.js (per guide)
- Run `mkdir my-app` to create a new folder my-app
- Run `cd my-app` to open the folder my-app
- Run `npm init` to create a package.json file
- Run `npm install --save-dev app-framework` to install App Framework and its dependencies
- At this point the `npm install` command stops with the error above

It seems that many people are having this same problem.
Also, what I already tried doing:
- Install previous versions 1.19.x, but it doesn't work either
- Install with `sudo`
- Install with and without `--save-dev`
- Tried to run `postinstall` manually, but there is no folder "app-framework" inside node_modules after the crash

Hope you can help me figure this out, as I need this fixed ASAP to build an app for a client of mine.
Thank you for your support.

**Comment by patrickpissurno** [comment]
Sorry, after I opened the issue, I tried to follow straight the docs and got it to install.
For other people that might have this same issue in the future:

You **can't** use `npm init` to create the package.json for `app-framework`. It will fail your installation!
Instead, use `echo {} > package.json`, run the `npm install --save-dev app-framework` to install it FIRST and then, complete the package.json file. **This is a must, really**.

Please close the issue as it is solved already.

**Comment by scriptPilot** [comment]
Yes, as described in the docs :-)
