### ISSUE TITLE
Hardware back button

### ISSUE THREAD

**Issue by daniel-centore** [scriptPilot/app-framework#772]
I'm trying out the sample app in Android and I would expect the hardware back button to behave the same way as the on-screen back button, bringing me to the previous page. Instead, it simply exits the app completely. Is there some way to rectify this?

**Comment by josteph** [comment]
By default, cordova lets you exit the app immediately if the hardware back button is pressed. You need to register the 'backbutton' listener in mounted:

```
const vm = this
document.addEventListener('backbutton', () => {
    vm.$f7.mainView.router.back()
}, false)
```

**Comment by scriptPilot** [comment]
In upcoming version V3, hardware APIs are managed by Capacitor. How to use the back button there is written here: https://capacitor.ionicframework.com/docs/apis/app/
