### ISSUE TITLE
Provide a way to get rid of Firebase

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#782]
What's the best way to get rid of firebase?

Reason: For my app I need persistent state-management, but no Firebase. But Firebase seems to be mixed in at different occasions.

So, what's the best way to get rid of the firebase connections & code? Is this possible at all?

If not, I'd suggest a feature request for this.

Personally I'd prefer vuex or localforage.

**Comment by scriptPilot** [comment]
@tiptronic  - In V3, all Firebase related integrations are to disable.
