### ISSUE TITLE
Allow removal of iFrame

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#783]
Since the app is loaded in an iframe, there are a couple of caveats when debugging and when trying to target browser/tablets, etc...

Can we get a switch to avoid loading the app in an iframe and instead use the browsers chrome?

**Comment by josteph** [comment]
Afaik, this project doesn't use iframe to load the app

**Comment by tiptronic** [comment]
I think you should look again 😉

**Comment by josteph** [comment]
Ah okay, I get your point. It's called `<div id="frame">...</div>`.

**Comment by tiptronic** [comment]
Jep - and if you try to debug things, vue-tools doesn't find the vue instance, because it can't access the iFrame.

**Comment by scriptPilot** [comment]
In V3, there is no more iFrame around the app ... if there will be some day, it will be configurable / to be disabled.
