### ISSUE TITLE
Anybody updated to F7v2?

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#785]
Is there anything going on with app-framework? 
Or do we consider this project as dead? (No pulls merged, no issues fixed, nobody has access to help out).

I like the idea of this framework pretty much, and it would be a great starting-point for any new project, but VueJS is already far into the 2.x.x and F7 made some pretty awesome changes, both of which we can't benefit from in app-framework.

So, has anybody already incuded F7v2?

**Comment by scriptPilot** [comment]
@tiptronic - Andy, you are right, there is the time for App Framework 2. I kindly invite you for your ideas in the following thread: https://github.com/scriptPilot/app-framework/issues/775

As you maybe know, I became a daddy last month and beside this major project I started a new position in my company. So - there is a conflict of priorities and as there have not been many more requests than your one, for me there was no chance to complete App Framework 2 in the last weeks.

Dead I will not say ... on hold currently ... ok.

**Comment by tiptronic** [comment]
@scriptPilot Thx for your answer! I surely understand your position, but I don't want to wait until it's getting better, so adding to [#775](https://github.com/scriptPilot/app-framework/issues/775) is not a real option, if the project is 'on hold'.

To me it would work just porting app-framework to F7V2 and then collect new ideas for another next major version (which would probably take a while until it works as expected).

Right now I'm using the 'regular' F7-vue-webpack package and manage everything else in XCode/Android Studio, which is pita compared to app-framework.
Using app-framework v1 is not really an option, since it doesn't play well with the iPhoneX and v2 has a much better performance and page-/style-handling. Also, it's highly confusing, when you need to lookup something in the docs, because you have to take exceptional care, if you currently read v1 or v2 docs.
I also started to write some scripts to easify common tasks, but I'm also new to webpack and lots of things are still unclear to me (and I also don't have time to work fulltime on those).

So any constructive idea is wholeheartedly welcome.

**Comment by scriptPilot** [comment]
I understand you have less time, not enough skills but want the Framework be updated asap - good combination :-D No, I am joking. So, for open source the point is not the money itself, it's time. I could reduce my ours at work to realize V2 soon, but then I need to get paid for 50 hours or so a different way - you have any idea? Second, if there should be better user contribution, the architecture could be more clearer. We should work on that in V2 as well. Referring to the post #775 - for me, the number of users contributing to it shows me in a way how much requested it is. For now, not much I understand.

**Comment by tiptronic** [comment]
Well tbh, I just need some information where to start - currently it's quite a bit information, what to change, and which consequences this has... But I'm digging through it and if I better understand what's going on, I'll here to help - no problem... there will always be a couple of hours time to do something (especially if it saves time in the long term).

As far as #775 is concerned: It's quite difficult to consider what should be going into V2, because I have a certain way how I (personally) work and what is important to me. I can add this, if you wish, but this would lead to a very stripped-down version of V1 😊 . E.g. for me, performance is #1, offline-first and state-restoration #2, Cordova/Android (plugin) handling #3 ... these are things that *every* application needs - everything else is optional.

Btw:Paying for 50 hours is only  just a question, how much you ask per hour 😊

**Comment by tiptronic** [comment]
1. Generally I don't care, if you use a payment-site or just Paypal, Patreon, Flattr, Bountysource or whatever...

2. I can't decide on what is a fair amount for you... that's your turn. All I can say: if it saves me time setting up my next project, I am happy to share... If you're going to create the setup-scripts to MY OWN desire, I'd pay even more 😉 (in that case - just drop me a pm)

Anyway: Donorbox/Donations is surely a good option to prioritize features. But they need to go along with a reliable time-frame then. Otherwise it's kinda pointless 😉

**Comment by ehausen** [comment]
Hello! Can a notice off Vue version be added to the top of readme, it at least somewhere visible?

"also maybe a contribution wanted" message/issue/note could be good.

Congratulations @scriptPilot, I do hope you manage to get some sleep and that everything is going well :)

**Comment by scriptPilot** [comment]
@ehausen - Thanks for your interest. What is in your mind when you take about detaching from Vue?

**Comment by josteph** [comment]
It's possible to update directly to F7 v3 instead. I've done several experiments including upgrading the webpack, etc.

**Comment by scriptPilot** [comment]
Next version will use Framework7 V3
https://github.com/scriptPilot/app-framework/issues/803
