### ISSUE TITLE
Firebase deployment fails: non-interactive mode not allowed

### ISSUE THREAD

**Issue by ehausen** [scriptPilot/app-framework#790]
Currently when trying to run `npm run firebase` to deploy to webapp it will not work and there is an error:

**Error: Cannot run login in non-interactive mode. See login:ci to generate a token for use in non-interactive environments.**

The script in `YOUR_APP_FOLDER/node_modules/app-framework/scripts/firebase.js` needs some fixing.

The crucial thing is at line 193:
` cmd(binFolder, 'firebase login', () => {`

**This should work, but does not: **
Currently you should go to command line and create a token by running `firebase login:ci` 
( first install firebase tools globally by running: `npm install -g firebase-tools`) and getting a token and then it should work like: `firebase login --token XXXXYYYYYZZZZZ`. But trying to put this into the script by editing that line did not work.

**Solution:** 
I edited the line 196  at `YOUR_APP_FOLDER/node_modules/app-framework/scripts/firebase.js` 
` cmd(binFolder, 'firebase login', () => {`
to be:
`cmd(binFolder, 'firebase login --interactive', () => {`

This allows you to interact with the command line. You might have to answer some questions before the command can finnish and if you are not logged in to firebase via cli, then it will open the browser window with google authentication.

**Comment by scriptPilot** [comment]
There is no more error in V3, if yes, please open a new issue.
