### ISSUE TITLE
How can i fix this problem views?

### ISSUE THREAD

**Issue by livewithme** [scriptPilot/app-framework#791]
![image](https://user-images.githubusercontent.com/16898982/40170289-9fe1820e-59fa-11e8-873d-3c87213e4151.png)
![image](https://user-images.githubusercontent.com/16898982/40170386-e12c7462-59fa-11e8-9ef5-1ace99732c41.png)

**Comment by livewithme** [comment]
![image](https://user-images.githubusercontent.com/16898982/40170524-341e5f3c-59fb-11e8-825a-d62efd57920f.png)

**Comment by livewithme** [comment]
![image](https://user-images.githubusercontent.com/16898982/40170979-948b8902-59fc-11e8-8f4f-9825e95fdb9e.png)
![image](https://user-images.githubusercontent.com/16898982/40170993-a1d0bd58-59fc-11e8-835d-d16ce6013937.png)
![image](https://user-images.githubusercontent.com/16898982/40171005-ae8dd67a-59fc-11e8-9f06-7833cdd236c0.png)
this mask is missing

**Comment by livewithme** [comment]
i find other way but like a bug: build error
![image](https://user-images.githubusercontent.com/16898982/40228789-db3fbb16-5ac4-11e8-8804-2abdb7dd9f9e.png)

**Comment by livewithme** [comment]
i find way,
![image](https://user-images.githubusercontent.com/16898982/40287757-2d1b2bae-5ce2-11e8-953f-703e680a39ab.png)
it can be will,

**Comment by livewithme** [comment]
![image](https://user-images.githubusercontent.com/16898982/40350741-3ad327a0-5ddd-11e8-9628-95dd78ac1e74.png)

**Comment by livewithme** [comment]
it happen some strange, when use multi-view 

![image](https://user-images.githubusercontent.com/16898982/40352364-39a0936e-5de1-11e8-8cd5-82bcb17eacf4.png)
![image](https://user-images.githubusercontent.com/16898982/40352415-55e4f8bc-5de1-11e8-9d55-1c2ee803cc42.png)

like this use $router.load({url:xxx}),some time will not jump to target page, like no responing

**Comment by scriptPilot** [comment]
If there will be still some issue with upcoming Framework V3, please reopen an issue.
