### ISSUE TITLE
Failed to install any version on macOS Sierra with NodeJS 8.11 LTS

### ISSUE THREAD

**Issue by a20185** [scriptPilot/app-framework#792]
Hello, I've just follow the installation instruction manual in your document.
However when I try to execute `npm install --save-dev app-framework` on my mac, it fails with showing the following message:

``` shell
npm ERR! Unexpected end of JSON input while parsing near '...download/webpack-4.4.'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Souler/.npm/_logs/2018-05-25T10_00_31_469Z-debug.log
```

The full log is attached below, hope it may helpful for analyzing the problem.

[2018-05-25T10_00_31_469Z-debug.log](https://github.com/scriptPilot/app-framework/files/2038936/2018-05-25T10_00_31_469Z-debug.log)

<img width="585" alt="ss" src="https://user-images.githubusercontent.com/14831358/40539320-f6470f0e-6046-11e8-9c68-7294313a95af.png">

**Comment by a20185** [comment]
@scriptPilot

**Comment by scriptPilot** [comment]
@a20185 - Please try again if there is still some error with V3 - hope not :-)
