### ISSUE TITLE
Add pdf (or any other filetype) to build assets

### ISSUE THREAD

**Issue by dleicht** [scriptPilot/app-framework#794]
My app is supposed to show pdf files.
The files are linked with simple href tags in the .vue files.
It works well with:
```
npm run dev
```

But whenever i try to build, the pdf files can not be found.
Webpack does not seem to include them? I tried to edit webpack-config.js accordingly, but to no avail.

How do i fix that?

**Comment by scriptPilot** [comment]
Possible in V3 as shown below:

```html
<p>
  <a href="./file.jpg" target="_blank" class="external">JPG Download</a>
</p>
<p>
  <a href="./file.pdf" target="_blank" class="external">PDF Download</a>
</p>
```

**Comment by dleicht** [comment]
Awesome, gonna try asap!
