### ISSUE TITLE
Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.

### ISSUE THREAD

**Issue by vvp3** [scriptPilot/app-framework#795]
how can I fix this please ?

Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

ps. Thank you for your template and I really hope I can manage to connect it to a small DB for a small app soon :)

**Comment by vvp3** [comment]
I installed Android Studi and error dissapeared.
Now I have this even if i have >11GB free. Is it becasue of a writing permission ? how can i manage it ?:

Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by vvp3** [comment]
i ran with --stacjtrace and nothing
sould i give you the log ?

**Comment by josteph** [comment]
Hi, can you provide the steps to reproduce the issue?

**Comment by vvp3** [comment]
I followed the steps on the documentation to install the needed software.
I tried the dev example and it works, it shows me on 8080 the screen.
I installed the Android Studio and i ran: npm run android.
After that i got the errors I told you. 
I tried many things after:
1. installed java sdk
2. installed choco and gradle
3. started a daemon with gradle --daemon
4. tried again, similar result ...
5. stopped the daeomn with --stop, tried again, similar result ...
6. made a simple file gradle.properties and put in it
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx1024m

Nothing works after many hours of debugging :(

I would just like to have your demo interface functional so I can begin work on js for the behaviours and connect to a mysql db.

**Comment by vvp3** [comment]
I think I solved that error reading some help over the internet and pointing manually the java home to an sdk folder in java developer jdk.
now i have this error

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 26].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

still i do not get how to run the demo to make it as a start project

**Comment by vvp3** [comment]
solved that too and for future newbies you have to go to Android Studio and check the SDKs (i did it untill 6.0)
after that I got this error and here I am really stuck (and again vexed becasue I cannot a have the template running "as advertised" and I do not find help in the documentation of how to do it.
here it is:

.....
BUILD SUCCESSFUL

Total time: 16.545 secs
Built the following apk(s):
        c:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
Built the following apk(s):
        c:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
Error: C:\Users\VP\AppData\Local\Android\sdk\platform-tools\adb.exe: Command failed with exit code 1 Error output:
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon

c:\Users\VP\my-app>Error: Cannot read property 'semver' of null

**Comment by vvp3** [comment]
ran taskkill /f /im adb.exe
ran again the npm android and got this

BUILD SUCCESSFUL

Total time: 3.604 secs
Built the following apk(s):
        c:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
Error: Cannot read property 'semver' of null

took out the 8.1 version from SDK and re-run

now i have this but nothing starting :(

BUILD SUCCESSFUL

Total time: 3.597 secs
Built the following apk(s):
        C:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
No emulator specified, defaulting to Android_Accelerated_x86_Oreo
**Waiting for emulator to start...**

**Comment by vvp3** [comment]
solved that too ... the 3 version of AS has some strange appearance of AVD manager but i managed to make it work and now everything works
nothing interesting happens though and I have some cordova errors it seems ...

i dont get it yet why all this have to happen --- i thought the framework can be ran on a localhost machine and this would have simplified a lot

**Comment by vvp3** [comment]
**maybe anyone/developer would find time to expliain how to use the demo as initial project and take into consideration all the errors and stuff needed to do to make it work**

i deleted all project and did the basic steps again (while i still have other softwares installed)
atm i have those erros and I am stopping since I invested too much time for no clear result

BUILD SUCCESSFUL

Total time: 16.155 secs
Built the following apk(s):
        c:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
Built the following apk(s):
        c:/Users/VP/my-app/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=C:\Users\VP\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172
Error: Cannot read property 'replace' of undefined

**Comment by josteph** [comment]
@vvp3 Yes app framework is able to run in localhost with command `npm run dev`. It also supports hot reload. But the drawback is, you won't be able to access cordova plugins as they are not installed for development.

If you want to really build with cordova (to test some plugins), you may do `npm run studio` or `npm run xcode`. It will install all your cordova plugins (can be found in config.json) and launch your xcode or android studio. This should be the normal working flow for testing on specific platform.
