### ISSUE TITLE
Problems doing a GET request

### ISSUE THREAD

**Issue by javiervaldeslz** [scriptPilot/app-framework#798]
Hi,

I have been following the documentation, but I have not been able to do a get - it does not fail, but nothing happens, and I am using a wiremock with verbose option and the request is not received, I have tested the mock with postman and any request is logged and working properly.

The code that I am testing is easy:

<template>
  <f7-page>
    <f7-navbar :title="$root.config.title" back-link="Back"/>

    <f7-button id="cheese" @click='cheese'>Cheese</f7-button>
  </f7-page>
</template>

<script>
  export default {
    methods: {
      cheese() {
        this.$f7.request({
          type: 'GET',
          url: 'http://localhost:8090/api/v1/cheese/1',
          data: { foo: 'bar', id: 5 },
          success() {
            this.$f7.alert('Load was performed')
          },
          error() {
            this.$f7.alert('Error')
          },
        })
      },
    },
  }
</script>

**Comment by josteph** [comment]
@javiervaldeslz Try to use `axios` instead of this. Also, consider of using other maintained Framework7-Cordova package than this one.

**Comment by scriptPilot** [comment]
If there is still some open question, please feel free to open a new issue.
