### ISSUE TITLE
Working with Firebase

### ISSUE THREAD

**Issue by inglesuniversal** [scriptPilot/app-framework#799]
I was able to create a Firebase account, set up users and it works... with the exception of viewing the TODOS since I get an error that there is some misconfiguration with Firebase. I am using the Build Folder... Do you have more detail instructions on how to access the same data by different users at the same time? TODOS Example is great.

**Comment by scriptPilot** [comment]
I do net get the point what is your question. If there is still some open point, please open a new issue.
