### ISSUE TITLE
Failed to parse package.json data. package.json must be actual JSON, not just JavaScript.

### ISSUE THREAD

**Issue by siz0001** [scriptPilot/app-framework#800]
after commend: npm install --save-dev app-framework , it happen. how to fix it?

npm ERR! file C:\Users\lenovo\Vueprojects\my-app\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
 pm ERR! Unexpected token � in JSON at position 0 while parsing near '��
npm ERR!  '
npm ERR! File: C:\my-app\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by scriptPilot** [comment]
Please correct the package.json file. If there are still issues in V3, please open a new issue.
