### ISSUE TITLE
v3  - add defaultPassword to config

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#893]
add defaultPassword parameter to config.js

**Comment by scriptPilot** [comment]
@tiptronic - I think storing passwords in plain text is a very unsecure architecture. So, if you have all other data as defaults ... only the password is to enter ... i think thats acceptable :-)

**Comment by tiptronic** [comment]
@scriptPilot Adding the ability doesn't mean, the user is FORCED to save his/her password.
If a user doesn't want to store it's password, he can leave the field just empty.
Removing the defaultPassword-option removes the ability to deploy automatically (or patch the files after every update, with is even worse).

And since the option is given in the ftp-deploy package, it seems to be some common behavior.

btw - in every Wordpress installation, the password is stored in the config file.
